### ISSUE TITLE
To generate device auth, please provide an exchange code for the email:

### ISSUE THREAD

**Issue by xero-lib** [Revadike/epicgames-freebies-claimer#104]
I've installed this through the AUR, and generated the device_auth,json and moved it to the read location.
I now try to run the program, and get `To generate device auth, please provide an exchange code for the email: [my email here]`

I have no idea what an "exchange code" is. I've checked my email, and nothing.

**Comment by Revadike** [comment]
You shouldn't be doing that. I don't think that part of the code was ever working. You use device authenticator tool, which is linked in the readme.

**Comment by xero-lib** [comment]
> You shouldn't be doing that. I don't think that part of the code was ever working. You use device authenticator tool, which is linked in the readme.

As stated in my initial comment, I did, and moved it to the requested locations.

**Comment by xero-lib** [comment]
> > You shouldn't be doing that. I don't think that part of the code was ever working. You use device authenticator tool, which is linked in the readme.
> 
> As stated in my initial comment, I did, and moved it to the requested locations.

Ah, it seems the initial device_auths.json was corrupted. Regenerating it seems to have fixed the problem.
