### ISSUE TITLE
about npm install errors

### ISSUE THREAD

**Issue by Cairl** [Revadike/epicgames-freebies-claimer#111]
![QQ截图20210624043353](https://user-images.githubusercontent.com/20336299/123164447-891cf200-d4a5-11eb-8596-6e8c733ac818.png)

i dont know why

**Comment by Revadike** [comment]
> i dont know why

![image](https://user-images.githubusercontent.com/4411977/123165746-e77dac80-d474-11eb-83b1-8a0648129c44.png)
