### ISSUE TITLE
Tutorial for lazy people (Programm will start on startup) ONLY WINDOWS 

### ISSUE THREAD

**Issue by Florian-Mahlberg** [Revadike/epicgames-freebies-claimer#116]
Hi,
I know, we are all lazy so, here is a tutorial for all WINDOWS 10 Users, to start this programm on startup.

First install like the Documentations says. I downloaded it in `D:\EpicGamesClaimer` so please change all directorys!

We need to edit the **claimer.js** file a bit, so we have no terminal on our screen. 

You go to line 109 and change the line `Logger.info(`Waiting ${delay} minutes`);` to `process.exit(0);`

Save it and we are done with this.

Press WIN + R and a window will open. Enter `taskschd.msc` and press enter.

In the bar at the top select `Create Task`.

Name it whatever you want and if you want to add a description. Tap on `Change User or Group...` and enter `System` in the big box. And press `OK`
- This runs the program by the system, so nothing could go wrong. If you are sure you don't want to to this and you have Admin rights, you don't need it.

Check the Box `Run with highest privileges`
-  Same thing here like the step before.

Check, if you have it like this:
![FirstStep](https://user-images.githubusercontent.com/53428387/123792730-3bf3b280-d8e1-11eb-8988-9e82dd9df921.JPG)

Go to triggers and create a new:
Change the dropdown `Begin the task:` to `At log on`
Activate `Stop task if it runs longer than:` and enter the time of 30 minutes

Compate it with the image to be sure, you dont forget anything:

![SecondStep](https://user-images.githubusercontent.com/53428387/123793091-a1e03a00-d8e1-11eb-8df9-8a7c10dd3894.JPG)

Save with `OK`

Now we are going to the Actions tab and click on `New..`

The Action should be `Start a program` by default.

In the Box `Program/script:` we enter the location of the npm command.  By default it is  `"C:\Program Files\nodejs\npm.cmd"` 

As arguments we use `--prefix <path> run start`
Change <path> to the location where you copied your files!!

We are checking again:
![ThirdStep](https://user-images.githubusercontent.com/53428387/123794953-bae9ea80-d8e3-11eb-8965-ddd850ad5331.JPG)

And closing this window by pressing `OK`.

Now just checking conditions for a sec:

![Fourth](https://user-images.githubusercontent.com/53428387/123795076-e53ba800-d8e3-11eb-929f-a410d49a84d3.JPG)

And edit in the settings tab a few things:

![FirstStep](https://user-images.githubusercontent.com/53428387/123795238-16b47380-d8e4-11eb-9bde-22ab358777f3.JPG)

And if everything is correct (by me and by you), we are now the laziest people I have ever seen. 
I hope I could help you out a bit.

**Some other stuff:**

If something is gone wrong, just comment, I should answer in a couple of days.

And if you, Revadike, are seeing this, it would be grat if you change the `README.md` a bit so everyone can see there is a option to run this on the start of the pc. 

If someone wants me to do a UNIX (Linux / MacOS tutorial please put it in the comments too ;) )

**Comment by Revadike** [comment]
[The wiki](https://github.com/Revadike/epicgames-freebies-claimer/wiki/Running-EpicGames-Freebies-Claimer#running-as-background-service-using-nssm-optional) is a better place for this. I linked to a section about running it as service via NSSM. I like your Windows Scheduler version too. Maybe put both methods in a separate page about running it as a service. Please, try to keep it nice and clean, use markdown.

> You go to line 109 and change the line `Logger.info(`Waiting ${delay} minutes`);` to `process.exit(0);`

You should simply change the `loop` option in the config to `false`...

> And if you, Revadike, are seeing this, it would be grat if you change the README.md a bit so everyone can see there is a option to run this on the start of the pc.

Again wiki. The wiki is also linked in README.md.

**Comment by Florian-Mahlberg** [comment]
Well happy to hear it comes to the wiki. Sorry for the markdown ^^  and yes, you could just change the loop.

**Comment by Revadike** [comment]
Anyone can edit the wiki

**Comment by Florian-Mahlberg** [comment]
Didn't know
