### ISSUE TITLE
This problem occurs after npm start

### ISSUE THREAD

**Issue by Cairl** [Revadike/epicgames-freebies-claimer#117]
![QQ图片20210701114941](https://user-images.githubusercontent.com/20336299/124062249-f7902000-da62-11eb-9aa5-0297cc084dcb.png)

sometimes these error codes appear, and sometimes they are normal, but this problem makes my daily collection very unstable

**Comment by Revadike** [comment]
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/100
