### ISSUE TITLE
Docker image asking for an "exchange code for email"?

### ISSUE THREAD

**Issue by jamespdaily** [Revadike/epicgames-freebies-claimer#118]
I'm running the Docker image on Ubuntu 21.04.  

I have device_auths.json in my local folder and run the docker image, however as it's starting up I see what's in the image below. The weird thing is if I start typing anything it doubles what I'm typing.

https://imgur.com/YoOx4ER

Could the issue be that I created device_auths.json on a different computer than the one that is running the docker container?

**Comment by Revadike** [comment]
Seems your format is wrong. It should be in JSON: <email>: { .... device auth data ... }
