### ISSUE TITLE
Getting this error when running npm install

### ISSUE THREAD

**Issue by Paleski** [Revadike/epicgames-freebies-claimer#121]
[2021-08-04T19_21_39_448Z-debug.log](https://github.com/Revadike/epicgames-freebies-claimer/files/6933927/2021-08-04T19_21_39_448Z-debug.log)

**Comment by jackblk** [comment]
Can you try all solutions in this: https://stackoverflow.com/questions/44316064/gyp-err-build-error-stack-error-make-failed-with-exit-code-2

If it doesn't work, try [Docker method](https://github.com/Revadike/epicgames-freebies-claimer/wiki/User-Guide-(Docker))

**Comment by labsin** [comment]
This seems to be the problem:
https://github.com/Revadike/node-epicgames-client/pull/10
Used dependency is 2y old...
