### ISSUE TITLE
exchange code for the email not received

### ISSUE THREAD

**Issue by zzz6839** [Revadike/epicgames-freebies-claimer#122]
When I try to run this program on Linux, an exchange code is required, but no email has been received on my mailbox, is it a bug or am I missing something?

 

log: 
root@Tower:~# docker run --rm --pull always -it --volume "$(pwd)/device_auths.json:/app/device_auths.json" --volume "$(pwd)/history.json:/app/history.json" ghcr.io/jackblk/epicgames-freebies-claimer:latest
latest: Pulling from jackblk/epicgames-freebies-claimer
Digest: sha256:e8e7e37553c3c3b2ce6ea3170d6e1dab04f8d54a52641c49440c3d93a6a45c79
Status: Image is up to date for ghcr.io/jackblk/epicgames-freebies-claimer:latest

> epicgames-freebies-claimer@1.5.3 start
> node claimer.js

 2021-08-06 | 11:19:36.802 | INFO  | Found 2 unclaimed freebie(s) for device_id
To generate device auth, please provide an exchange code for the email: device_id :

**Comment by Revadike** [comment]
Yeah, that doesn't work. You're supposed to generate auth with device auth generator.
