### ISSUE TITLE
internal/modules/cjs/loader.js:96

### ISSUE THREAD

**Issue by stickerx** [Revadike/epicgames-freebies-claimer#124]
### Background (if needed)
![2021-09-09_210529](https://user-images.githubusercontent.com/41187653/132763482-402990e8-0fa9-40ff-8107-919130f7a450.jpg)

![2021-09-09_211430](https://user-images.githubusercontent.com/41187653/132763624-056c6dc8-9846-4de8-8dc9-ab2f337ae396.jpg)

**Comment by Revadike** [comment]
yeah, so I guess the wiki got updated too soon, but anyways, reinstall the claimer with the latest github files, that should work I think
