### ISSUE TITLE
(CHANGE THIS!) A Question?

### ISSUE THREAD

**Issue by flameleo11** [Revadike/epicgames-freebies-claimer#126]
### when client.init() throw a error 
 
Error: WaitingRoom error: Error: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established

	const client = new Launcher({
	  email: userinfo.email,
	  password: userinfo.password,
	  debug: console.log,
	});
	var ret = await client.init()
	print(111, ret)

### Background (if needed)
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

node -v
v14.16.1

**Comment by Revadike** [comment]
What?
