### ISSUE TITLE
Update/provide new method to get device_auths.json

### ISSUE THREAD

**Issue by fatinghenji** [Revadike/epicgames-freebies-claimer#127]
### Current Behavior (if any)

1. By using DeviceAuthGenerator.exe to get the file I should get.
2. DeviceAuthGenerator.exe runs with an error.
3. This issue has been raised in [DeviceAuthGenerator-issue3](https://github.com/xMistt/DeviceAuthGenerator/issues/3), but has never been fixed.
### Desired Behavior
Get the available` device_auths.json` file
### Motivation / Use Case for Changing the Behavior
Normal deployment and use of EpicGames Freebies Claimer

**Comment by Revadike** [comment]
Well, I am trying to adopt a native method, by using the `fnbrjs` library (check the `fnbrjs` branch), but I am struggling to implement it properly. I cannot figure out how to authenticate to the epic game store. The part I struggle with is generating cookies for the epic game store.

**Comment by aneem** [comment]
**Note:** This is a workaround i found which works. Its a bit tedious and manual at this point. 😔😔

The DeviceAuthGenerator throws error, however i was able to get the info required for `device_auths.json` by following the instructions [here](https://github.com/MixV2/EpicResearch/blob/master/docs/auth/grant_types/device_auth.md). These are the steps I followed:
1. Ensure you are logged into epicgames with you account in ur browser
2. Get `authorization_code` by opening this [link](https://www.epicgames.com/id/api/redirect?clientId=3446cd72694c4a4485d81b77adbb2141&responseType=code) in browser. The client id i've used is for `fortniteIosClient`. 
3. Get access code by using the authorization code from step 2. 
```
curl --location --request POST 'https://account-public-service-prod.ol.epicgames.com/account/api/oauth/token' \
--header 'Authorization: Basic MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=authorization_code' \
--data-urlencode 'code={{code_from_step_2}}'
```
4. Use the access code from step 3 to get the details using the following curl
```
curl --location --request POST 'https://account-public-service-prod.ol.epicgames.com/account/api/public/account/{{your_account_id}}/deviceAuth' \
--header 'Authorization: Bearer {{bearer_token_from_step_3}}'
```
5. You still need to manually store the response in the `device_auths.json` with your email as json key.

However even after doing so and creating the `device_auths.json` file, when running the claimer.js, it was still asking for exchange code.
As a work around, i got the exchange code from following instructions [here](https://github.com/MixV2/EpicResearch/blob/master/docs/auth/grant_types/exchange_code.md) and tweaked the code in `claimer.js` as shown in the screenshot.
![image](https://user-images.githubusercontent.com/5670204/134223881-88c88881-4768-4e9f-8353-1de762048ec8.png)

Not sure if this is all the effort, but for someone who is looking for a quick fix this will work.
Hope this helps!

**Comment by jackblk** [comment]
Wow I didn't know https://github.com/MixV2/EpicResearch exists. Thanks for document, it helps :).

I also have the same issue with [DeviceAuthGenerator-issue3](https://github.com/xMistt/DeviceAuthGenerator/issues/3) and with the document, I think I fixed the issue. Will push a patch to my fork after I do more test.

**Comment by jackblk** [comment]
I fixed the issue with DeviceAuthGenerator here: https://github.com/xMistt/DeviceAuthGenerator/issues/3#issuecomment-924350309

I think we can continue to use this method to export the tokens.

**Comment by Revadike** [comment]
Well, if we can make the `fnbrjs` library working, we no longer have to rely on third party apps, or abandoned libraries. :)

**Comment by stickerx** [comment]
@Revadike after generating device_auths.json from my account keeps asking me to provide an exchange code for the email

?

**Comment by Revadike** [comment]
> @Revadike after generating device_auths.json from my account keeps asking me to provide an exchange code for the email
> 
> ?

Is it in the right folder?

**Comment by stickerx** [comment]
@Revadike  yes data folder

**Comment by fatinghenji** [comment]
> > @Revadike after generating device_auths.json from my account keeps asking me to provide an exchange code for the email
> > ?
> 
> Is it in the right folder?
Experiencing the same problem
The program prompts are as follows：
`To generate device auth, please provide an exchange code for the email:example@example.com`

**Comment by Revadike** [comment]
Make sure all your installations are up-to-date. Please don't hijack this issue.
