### ISSUE TITLE
(generate device auth!) exchange code?

### ISSUE THREAD

**Issue by stickerx** [Revadike/epicgames-freebies-claimer#128]
### Details
after Generate device_auths.json (using DeviceAuthGenerator)

keep asking me for an exchange code

### Background (if needed)
![2021-09-22_135038](https://user-images.githubusercontent.com/41187653/134347540-9997cfad-718f-4ef4-bef1-8578a8cd31d7.jpg)

**Comment by jackblk** [comment]
Have you tried to generate it again with the latest version of DeviceAuthGenerator?

https://github.com/jackblk/DeviceAuthGenerator/releases/tag/1.1.1

**Comment by stickerx** [comment]
yes I generated "device_auths.json" with your own release the latest version

**Comment by Agape2077** [comment]
Same issue
Here is the screenshot
![IMG_20210922_220758](https://user-images.githubusercontent.com/14299947/134359385-656ed4e8-5529-4bc2-b61b-7bf4b1dd1032.jpg)

**Comment by Agape2077** [comment]
and when i copied auth json file from data floder to root and it's resolved....

**Comment by Revadike** [comment]
Yeah, it depends on what date you downloaded the project. The location of the json files recently got updated, but the version wasn't incremented.

**Comment by stickerx** [comment]
the date you downloaded the project is today

**Comment by jackblk** [comment]
@Revadike I guess you need to release 1.5.4 with a clearer log to remind user what's missing 😄

**Comment by Agape2077** [comment]
I just clone the project when i send the screenshot maybe release version fixed this issue but I'm not tested it

**Comment by jackblk** [comment]
@stickerx you still have this problem? I created a new account and tested, I cannot reproduce this issue.

Can you try [Docker method](https://github.com/Revadike/epicgames-freebies-claimer/wiki/User-Guide-(Docker))?

**Comment by stickerx** [comment]
@jackblk Docker Desktop is not supported on Windows 7

**Comment by jackblk** [comment]
@stickerx can you create a new dummy account and try claiming?
If the issue happens again, please share the dummy account with me, then I will try to debug the issue.

**Comment by stickerx** [comment]
@jackblk  thanks are working now
