### ISSUE TITLE
any idea why this error appears?

### ISSUE THREAD

**Issue by B0tul** [Revadike/epicgames-freebies-claimer#129]
I followed all of the instructions and tried to run the program but it throws this error at me, I tried reinstalling but that didnt help, is there something im missing?
![123](https://user-images.githubusercontent.com/31157167/134360894-dc16d3f6-6e70-4b6a-b7fa-98064f85b3c9.png)

**Comment by Revadike** [comment]
Cannot find module `epicgames-client`.

**Comment by jackblk** [comment]
You can try Docker method, you only need to install Docker.

**Comment by jackblk** [comment]
@cobadulu001 I updated the [wiki for docker cmd/powershell](https://github.com/Revadike/epicgames-freebies-claimer/wiki/User-Guide-(Docker)#windows)

The commands are for CommandLine, try again with CMD. If you prefer Powershell then replace `%cd%` with `$(pwd)`

I'm sure it will work.
