### ISSUE TITLE
TypeError in getOffer

### ISSUE THREAD

**Issue by rickyelopez** [Revadike/epicgames-freebies-claimer#134]
### Actual Behavior
```
> node claimer.js

 2021-10-14 | 15:24:25.045 | ERROR | TypeError: Cannot read properties of null (reading 'split')
    at getOffer (/app/src/gamePromotions.js:14:54)
    at /app/src/gamePromotions.js:17:27
    at Array.map (<anonymous>)
    at freeGamesPromotions (/app/src/gamePromotions.js:16:45)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/claimer.js:72:30
```

### Steps to Reproduce the Problem

  1.  pull latest image from docker
  2.  `docker-compose run epic_free`

### Specifications

Running using docker-compose instructions, pulled latest image

### Notes
This was working previously, stopped working today.

**Comment by jackblk** [comment]
This bug is not related to device auth, just wait for a fix.

**Comment by jackblk** [comment]
Hmm I'm also sniffing the traffic, from the addon page, but I didn't find that one. What action do you do (or visit which page) to get that one?

**Comment by jackblk** [comment]
Yeah, we can handle it by checking `"offerType": "ADD_ON"` too. If it is an addon then we do specific function for `getOffer()`, otherwise we just use the client like normal.

**Comment by rickyelopez** [comment]
When will the docker image be updated? Does it happen automatically?

**Comment by jackblk** [comment]
Docker image is updated. Sorry for the delay, it was 2AM when v1.5.5 was released lol.
