### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Lucetia** [Revadike/epicgames-freebies-claimer#142]
### Expected Behavior

For it to start the program.

### Actual Behavior
```
pi@RPI4:~/EpicFreebies $ npm start
npm WARN npm npm does not support Node.js v10.24.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/

> epicgames-freebies-claimer@1.5.5 start
> node claimer.js

internal/modules/cjs/loader.js:638m:load:cleanupLog Completed in 7ms
    throw err;
    ^

Error: Cannot find module '/home/pi/EpicFreebies/data/device_auths.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/EpicFreebies/claimer.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### Steps to Reproduce the Problem

  1.  Run Claimer then fails
  2.  Updated then claimer fails
  3.  Updated the Device_Auths.json file and still failed.
  4.  Tried updating npm but no luck

### Specifications

  - `epicgames-freebies-claimer` Version:  claimer.js version is 1.5.4, readme/package.json is 1.5.5
  - Platform / OS:  Raspbian / Ubuntu
  - Node Version:  10.24.1
  - NPM version: 8.1.0

**Comment by jackblk** [comment]
Dup with https://github.com/Revadike/epicgames-freebies-claimer/issues/141#issuecomment-947407541

Put `device_auths.json` in `/data` folder.

Btw if you use Rasp then docker method is better for you to get update

**Comment by adi170-alt** [comment]
> Dup with [#141 (comment)](https://github.com/Revadike/epicgames-freebies-claimer/issues/141#issuecomment-947407541)
> 
> Put `device_auths.json` in `/data` folder.
> 
> Btw if you use Rasp then docker method is better for you to get update

hi, I am on linux(debian) with docker, where can I find the data folder because it is kind of confusing

**Comment by jackblk** [comment]
> hi, I am on linux(debian) with docker, where can I find the data folder because it is kind of confusing

If you use Linux & Docker, make sure you are in the folder that has `device_auths.json`, then just run this command in the [User Guide](https://github.com/Revadike/epicgames-freebies-claimer/wiki/User-Guide-(Docker)#maclinux)
