### ISSUE TITLE
wiki screenshot needs to be updated

### ISSUE THREAD

**Issue by lupohan44** [Revadike/epicgames-freebies-claimer#146]
### Expected Behavior
N/A

### Actual Behavior
In [Installing EpicGames Freebies Claimer](https://github.com/Revadike/epicgames-freebies-claimer/wiki/Installing-EpicGames-Freebies-Claimer), device_auth.json still in root folder, it has been moved into data folder

### Steps to Reproduce the Problem
N/A

### Specifications

  - `epicgames-freebies-claimer` Version: N/A
  - Platform / OS: N/A
  - Node Version: N/A

**Comment by lupohan44** [comment]
if https://github.com/Revadike/epicgames-freebies-claimer/pull/145 this PR merged, [Running EpicGames Freebies Claimer](https://github.com/Revadike/epicgames-freebies-claimer/wiki/Running-EpicGames-Freebies-Claimer)'s config.json section needs to be modified too

**Comment by lupohan44** [comment]
Wrong lable, sorry, it should be enhancement

**Comment by Revadike** [comment]
@lucifudge u think you could update the screenshot? You're the original wiki page author.
