### ISSUE TITLE
Docker auto run every week

### ISSUE THREAD

**Issue by adi170-alt** [Revadike/epicgames-freebies-claimer#147]
Hi I am running docker on my Raspberry Pi 4(Debian) and my question is i it is possible to auto run it every week or like every 2 days if needed, maybe I didn't read it right, but it seems like there is nothing about docker autostart(only windows) so again, my question is if it is possible to have docker autorun this(for example npm run)
(I have my Raspberry Pi always turned on)

**Comment by Revadike** [comment]
In `config.json` you can configure it to autoloop every week.

**Comment by jackblk** [comment]
If you use Docker on Rasp, you can use [Cron to schedule](https://www.raspberrypi.com/documentation/computers/using_linux.html#scheduling-tasks-with-cron)

If you want to use `systemd` then it's in the same link. You will need to read and config a little bit though.

**Comment by adi170-alt** [comment]
> In `data/config.json` you can configure it to autoloop every week.

Thank u, that worked!
(Earlier I didn't have config.json because I just git cloned this repository)
(I use tmux to let it run in the background)
