### ISSUE TITLE
Game xy is already Claimed.

### ISSUE THREAD

**Issue by Jaeger33211Sec** [Revadike/epicgames-freebies-claimer#149]
### Expected Behavior
Claim all Games

### Actual Behavior
Bot trys to claim, says: Game is already claimed.
After the next run the Bot says 0 free Games availabe but there are some.
t

### Steps to Reproduce the Problem

  1. Have Multiple Accounts (100+) 
  2. Try to Bot
  3. Look in the Accounts what Games are owned.

Some Accounts are working but not all.

### Specifications

  - `epicgames-freebies-claimer` Version: 1.5.5
  - Platform / OS: Windows 10 21H1
  - Node Version: V16.2.0

**Comment by Revadike** [comment]
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/115
