### ISSUE TITLE
DeviceAuthGenerator fail create auth

### ISSUE THREAD

**Issue by ZombiePm** [Revadike/epicgames-freebies-claimer#150]
[https://github.com/xMistt/DeviceAuthGenerator/issues/11](url)
{
    "errorCode": "errors.com.epicgames.common.oauth.invalid_token",
    "errorMessage": "Client id mismatch in credentials for this pin grant",
    "messageVars": [],
    "numericErrorCode": 1012,
    "originatingService": "com.epicgames.account.public",
    "intent": "prod",
    "error_description": "Client id mismatch in credentials for this pin grant",
    "error": "invalid_grant"
}

**Comment by Revadike** [comment]
do u have the latest version? You must compile it yourself

**Comment by jackblk** [comment]
1. This is an issue from DeviceAuthGenerator, not EFC
2. That issue is fixed, in issue https://github.com/xMistt/DeviceAuthGenerator/issues/3#issuecomment-924350309

**Comment by Revadike** [comment]
@xMistt

**Comment by ZombiePm** [comment]
[https://github.com/jackblk/DeviceAuthGenerator](url) working fork DeviceAuthGenerator
