### ISSUE TITLE
Log to discord bot or discord webhook

### ISSUE THREAD

**Issue by baguay1** [Revadike/epicgames-freebies-claimer#153]
Make it possible to log to a discord bot or discord webhook :)

**Comment by jackblk** [comment]
It's already available via apprise: https://github.com/caronc/apprise#popular-notification-services

Configure it in `config.json` file, it will look something like this:

```json
{
    "appriseUrl": "discord://webhook_id/webhook_token",
    "delay": 1440,
    "loop": false,
    "options": {}
}
```
