### ISSUE TITLE
Apprise error: Failed to send push notification 

### ISSUE THREAD

**Issue by spabaex** [Revadike/epicgames-freebies-claimer#158]
Everything works fine except send notification.
**I got error "ERROR | Failed to send push notification (ERROR: Maybe apprise not found?)"**
```
config.json
{
        "appriseUrl": "tgram://203******25:AAEXfUX8sghhXDlvaE*******uhIaSNgUs/1840****28/",
        "options": {},
        "delay": 1440,
        "loop": true
}

```
What I do:
```
npm install 
pip install apprise
setup config.json, device_auths.json
node claimer.js
```
OS: Ubuntu Server 20.04 LTS
Thanks in advance <3

**Comment by Revadike** [comment]
I believe you must put the apprise application in the root folder of epicgames-freebies-claimer.

**Comment by jackblk** [comment]
Did you install apprise?

You will need Python >= 3.6 and you can install with `pip install apprise`

If you know how to use virtual env, it is better to use virtual env: https://docs.python.org/3/library/venv.html

@Revadike this is one of the reason why I want to include apprise in the main image, we can guide people to use the main image, less error or question like this. After merging #157 I will update the wiki for apprise.

**Comment by jackblk** [comment]
I've updated all wiki pages

* [User guide for docker](https://github.com/Revadike/epicgames-freebies-claimer/wiki/User-Guide-(Docker)) @spabaex you should use docker image to run & update easily
* [Config apprise](https://github.com/Revadike/epicgames-freebies-claimer/wiki/Notification-with-Apprise)

**Comment by lucifudge** [comment]
> I've updated all wiki pages
> 
>     * [User guide for docker](https://github.com/Revadike/epicgames-freebies-claimer/wiki/User-Guide-(Docker)) @spabaex you should use docker image to run & update easily
> 
>     * [Config apprise](https://github.com/Revadike/epicgames-freebies-claimer/wiki/Notification-with-Apprise)

Can you provide examples for Discord?

**Comment by jackblk** [comment]
@lucifudge check out Apprise syntax: https://github.com/caronc/apprise#popular-notification-services

You can see an example for discord there
