### ISSUE TITLE
"Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by PatiB87** [Revadike/epicgames-freebies-claimer#163]
Hey,
the tool now only gives me "Cannot read property 'id' of undefined" as error.
Is that a bug?

Cheers

**Comment by PatiB87** [comment]
Nevermind! Sorry!! Current version fixed it!

**Comment by Revadike** [comment]
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/159
