### ISSUE TITLE
Using creator code when claiming games

### ISSUE THREAD

**Issue by nameless-droid** [Revadike/epicgames-freebies-claimer#164]
### Current Behavior (if any)

doesn't use a creator code for claiming games

### Desired Behavior

option to write creator code in config.json
and the program should use the code when purchasing

### Motivation / Use Case for Changing the Behavior

supporting creators

**Comment by Revadike** [comment]
Is it useful for free games too?

**Comment by nameless-droid** [comment]
useful idk, sometimes you can use it on free games, this week for example

**Comment by Revadike** [comment]
Well, if you want someone to spend their time on it, it should at least be useful, imo.

**Comment by nameless-droid** [comment]
Ok, sorry.
