### ISSUE TITLE
Disable Push Notification When No Freebies Are Found

### ISSUE THREAD

**Issue by EthanC** [Revadike/epicgames-freebies-claimer#165]
### Current Behavior

- A push notification with the following message will be sent to the configured `appriseUrl` each time the app is run...
> Epicgames Freebies Claimer 1.5.7
> example@email.com has no unclaimed freebies

https://github.com/Revadike/epicgames-freebies-claimer/blob/17222e8a575d1854febbe5a47af8f8f14b37e3fd/claimer.js#L98

### Desired Behavior

- A push notification should only be sent upon error (#151) or successful claim.

### Motivation / Use Case for Changing the Behavior

- This push notification is unnecessary, it's essentially saying "I've done nothing because there is nothing for me to do right now." By limiting push notifications to those that are informative, we can increase the viability of this logging addon.

**Comment by jackblk** [comment]
Seems fair. I will fix it soon, maybe we will deploy in 1.5.8.

**Comment by cobadulu001** [comment]
Idk, but i find it (that notification) useful. Because sometime i just forget if i already claimed freebies or not, so i just run the script to know if theres any unclaimed games

**Comment by jackblk** [comment]
> Idk, but i find it (that notification) useful. Because sometime i just forget if i already claimed freebies or not, so i just run the script to know if theres any unclaimed games

* If there's no notification: everything is OK: you have claimed everything, config is ok (apprise config should be working in the first place though)
* If there's a notification:
  * Something broken: it will tell you what went wrong
  * You claimed something

**Comment by Revadike** [comment]
We can always have an option for this in the config.
