### ISSUE TITLE
Error when claiming new mystery games

### ISSUE THREAD

**Issue by solomonricky** [Revadike/epicgames-freebies-claimer#166]
Outcome with error when claiming Shenmue III 

_Failed to claim Shenmue III (Error: Unable to acquire purchase token)_

### Specifications

  - `epicgames-freebies-claimer` Version: v1.5.7
  - Platform / OS: Debian

**Comment by fIows** [comment]
It isn't an issue with the program. It currently doesn't work as well when doing it normally. The issue is most likely a server issue and will start working in a couple of hours.

**Comment by mamanlust** [comment]
Same error ocured on automated github action solution

- Image: ghcr.io/jackblk/epicgames-freebies-claimer:latest
- Operating System: Ubuntu 20.04.3

**Comment by ProblemFactory** [comment]
It is showing a new error now:
```
ERROR | TypeError: Cannot destructure property 'elements' of 'data.Catalog.searchStore' as it is null.
    at freeGamesPromotions (/app/src/gamePromotions.js:45:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/claimer.js:91:30
```

- epicgames-freebies-claimer Version: v1.5.7 
- Platform / OS: Debian (ARM 64)

**Comment by mamanlust** [comment]
Tried to get the game by hand, and EGS site is going nuts, can't even get the game manually, maybe this is the problem?

**Comment by cobadulu001** [comment]
I got a problem too when claiming new mystery game
![Screenshot_20211217-052207_Iceraven](https://user-images.githubusercontent.com/67148484/146457975-b440cdcb-b60f-418f-836e-d3341da7a09f.png)


    epicgames-freebies-claimer Version: v1.5.7
    Platform / OS: Github Workflow

**Comment by TovMachin** [comment]
Same problem here ...

Screenshot: [https://i.postimg.cc/cJ5911vD/Capture.png](url)

**Comment by wubushanyan** [comment]
> Same problem here ... [Screenshot](https://i.postimg.cc/cJ5911vD/Capture.png)

Same ，but it claimed the game in fact

**Comment by Nuevo009** [comment]
Same error... Seems that the site is broken?
```shell
> epicgames-freebies-claimer@1.5.7 start
> node claimer.js

 2021-12-17 | 03:14:36.073 | INFO  | Epicgames Freebies Claimer (1.5.7) by Revadike
 2021-12-17 | 03:14:39.958 | INFO  | Found 1 unclaimed freebie(s) for xxx@xxx.com
 2021-12-17 | 03:14:45.982 | INFO  | Logged in xxx(xxx@xxx.com)
 2021-12-17 | 03:14:48.473 | WARN  | Failed to claim Shenmue III (Error: Unable to acquire purchase token)
 2021-12-17 | 03:14:49.568 | INFO  | Logged xxx out of Epic Games
 2021-12-17 | 03:15:01.585 | INFO  | Push notification sent
 2021-12-17 | 03:15:01.588 | INFO  | Waiting 120 minutes
```
* Image: ghcr.io/jackblk/epicgames-freebies-claimer:latest
* Operating System: Ubuntu 20.04.3 arm64v8

> but it claimed the game in fact


And it did not claim the games for me here. I try to reduce the interval to see if it succeeds.

**Comment by chenyitian2004** [comment]
Another developer of a similar project said that epic has replaced a new order link, and the previous one seems to be unusable: https://github.com/luminoleon/epicgames-claimer/issues/60#issuecomment-996355791

**Comment by lucifudge** [comment]
same

**Comment by jackblk** [comment]
I tested and I see 2 possible errors:

* Error: ESOCKETTIMEDOUT
* Error: Unable to acquire purchase token

It seems like the timeout error also happens on web 😄

**Comment by T1MOXA** [comment]
![image](https://user-images.githubusercontent.com/19938629/146492527-cb3cfc54-8f7b-4dca-910c-54343989ef07.png)


> I tested and I see 2 possible errors:
> 
> * Error: ESOCKETTIMEDOUT
> * Error: Unable to acquire purchase token
> 
> It seems like the timeout error also happens on web 😄

Yup

**Comment by ProblemFactory** [comment]
I tried to claim the free game manually. It worked after several (<10) attempts, but the epicgames-freebies-claimer has never succeeded on any of the 3 accounts I setup. I think there must be some issues on the claimer end, instead of EGS end.

**Comment by Zerlingg** [comment]
Same here

**Comment by ridai260** [comment]
Same issue, thought it was my token and refreshed several times. "Failed to claim Shenmue III (Error: Unable to acquire purchase token)."

**Comment by TovMachin** [comment]
> I tried to claim the free game manually. It worked after several (<10) attempts, but the epicgames-freebies-claimer has never succeeded on any of the 3 accounts I setup after hundreds of attempts. I think there must be some issues on the claimer end, instead of EGS end.

Claiming it manually worked instantly for me.

**Comment by Revadike** [comment]
> 

You mean this?
https://github.com/luminoleon/epicgames-claimer/commit/83d2707f7552ac9a0907ba877f9de658a1fc5680

This project uses a whole different approach, sadly. It uses a whole internet browser and automate user-actions. It's something I considered myself, but the approach I am currently (with just HTTP requests) using is way more lightweight and doesn't depend on the user interface.

**Comment by chenyitian2004** [comment]
> > Another developer of a similar project said that epic has replaced a new order link, and the previous one seems to be unusable: [luminoleon/epicgames-claimer#60 (comment)](https://github.com/luminoleon/epicgames-claimer/issues/60#issuecomment-996355791)
> 
> 
> 
> 
> 
> 
> 
> You mean this?
> 
> https://github.com/luminoleon/epicgames-claimer/commit/83d2707f7552ac9a0907ba877f9de658a1fc5680
> 
> 
> 
> This project uses a whole different approach, sadly. It uses a whole internet browser and automate user-actions. It's something I considered myself, but the approach I am currently (with just HTTP requests) using is way more lightweight and doesn't depend on the user interface. 

Yes, I quote this example mainly to confirm that Epic enables the new order address, which may lead to this error.

**Comment by CriticalE** [comment]
Hello guys, sorry for ask again, so no solution for this? got same message about token and no work to claim games :(

**Comment by Revadike** [comment]
I probably won't have any time to look into this, this weekend. Feel free to investigate yourself (and submit a PR). You could use debugger tools, http requests monitor or simple logging to figure out exactly what is going wrong. From what I've seen, it's something EGS changed in the purchase flow.

**Comment by zjbthomas** [comment]
Just did some debugging and I currently have a feeling that Epic blocks the access from [node-epicgames-client](https://github.com/Revadike/node-epicgames-client), which is the underlying framework for this project.

When using this client to access `ue-launcher-website-prod.ol.epicgames.com`, Epic always returns `Error 500` with `We are currently doing some updates to the site.`, which is actually not the case - if you directly visit `https://${ENDPOINT.PORTAL_ORIGIN}/purchase?showNavigation=true&namespace=${offer.namespace}&offers=${offer.id}` with the same namespace and ID in any browser, the order page can be correctly shown. So Epic's servers should be fine.

I believe this requires some changes in the underlying [node-epicgames-client](https://github.com/Revadike/node-epicgames-client) to trick Epic. For those who are also interested in it, you can find where the `purchaseToken` is retrieved in lines 592 to 599 of this [index.js](https://github.com/Revadike/node-epicgames-client/blob/develop/src/Client/index.js) file.

**Comment by XEGARE** [comment]
With the help of @zjbthomas, I found that when manually navigating in the browser by
`https://ue-launcher-website-prod.ol.epicgames.com/purchase?showNavigation=true&namespace=d5241c76f178492ea1540fce45616757&offers=a0bb13a219f747f88dff4c2a50b070c0` the page says a `Error 500,` but the **purchaseToken** is in the **URL**

**Comment by jackblk** [comment]
@XEGARE I think your namespace is not correct, this works for me:

`https://ue-launcher-website-prod.ol.epicgames.com/purchase?showNavigation=true&namespace=663e521f2a444199be58152fd93fa66e&offers=a0bb13a219f747f88dff4c2a50b070c0`

**Comment by XEGARE** [comment]
@jackblk This also worked for me, but I got my namespace like this:
`console.log(`namespace=${offer.namespace}`);`
`console.log(`offers=${offer.id}`);`

But one way or another, but the **purchaseToken** is in the URL of both variants

**Comment by zjbthomas** [comment]
Thanks @XEGARE for following up. I am now able to retrieve the `purchaseToken`, but the issue is more than that.

Just as a reference, my way to get the `purchaseToken` is:
```
async newPurchase(offer) {
    let { response: res } = await this.http.sendGet(`https://${ENDPOINT.PORTAL_ORIGIN}/purchase?showNavigation=true&namespace=${offer.namespace}&offers=${offer.id}`);
    let query = url.parse(res.request.href, true).query;
    const token = query['purchaseToken'];
    return {
      token,
    };
  }
```

In the next step, a post request should be sent to the `order-preview` page (see function `purchaseOrderPreview()` in line 601 of [index.js](https://github.com/Revadike/node-epicgames-client/blob/develop/src/Client/index.js)). This will throw an error `Error: There was a problem processing your request.  Please try again later.` in line 628.

I currently do not have enough spare Epic accounts to sniff the traffics for such step. Any help will be appreciated.

**Comment by XEGARE** [comment]
@zjbthomas I don't know exactly, Remnant: From the Ashes has been handed out before. Today I picked up the game again by hand and was asked for confirmation. Perhaps you have something to do with this (if you have already taken the game before). I have such an error `ReferenceError: url is not defined`

**Comment by XEGARE** [comment]
@zjbthomas My `console.log (data);` in **purchaseOrderPreview** issued a **syncToken**. I commented out `throw new Error (data.orderResponse.message);` in **purchaseOrderPreview** and got `WARN | Remnant: From the Ashes was already claimed for this account`

I will do so for now. I'll see what happens tomorrow
```
    let message = data.orderResponse.message;
    if (data.orderResponse && data.orderResponse.error && !message.includes('There was a problem processing your request.')) {
      throw new Error(message);
    }
```

**Comment by jackblk** [comment]
Huh, I think I found the problem why server responds with 500 on our claimer, but not the browser.

Here's the actual curl to get `purchaseToken` for Remnant: From the Ashes, taken from the browser:

```shell
curl 'https://ue-launcher-website-prod.ol.epicgames.com/purchase?showNavigation=true&namespace=663e521f2a444199be58152fd93fa66e&offers=a0bb13a219f747f88dff4c2a50b070c0' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36' \
  -H 'cookie: EPIC_BEARER_TOKEN=your_bearer_token_here;' \
  --compressed
```

Here's the curl in our claimer client (Authorization header is not needed):

```shell
curl 'https://ue-launcher-website-prod.ol.epicgames.com/purchase?showNavigation=true&namespace=d5241c76f178492ea1540fce45616757&offers=a0bb13a219f747f88dff4c2a50b070c0' \
  -H 'cookie: EPIC_BEARER_TOKEN=your_bearer_token_here;' \
  --compressed
```

Notice the diff? It's the namespace lol.

Apparently the namespace in [freeGamesPromotions API](https://store-site-backend-static-ipv4.ak.epicgames.com/freeGamesPromotions?locale=en-US) is not correct.

What I did:

* Put a breakpoint here: https://github.com/Revadike/epicgames-freebies-claimer/blob/17222e8a575d1854febbe5a47af8f8f14b37e3fd/claimer.js#L116
* In debug console, when it stops at that line, enter: `offer.namespace = "663e521f2a444199be58152fd93fa66e"`
* Continue

Now it will respond with 200, the purchase token will load correctly.

I haven't tested fully to see if it can buy the game or not, because if I buy it, I will not have any account left to claim (lol). But I think this is the root cause, you can try it out yourself 😄

**Comment by Revadike** [comment]
@jackblk was right. The free games API is returning the wrong namespace. I'll soon release a workaround that grabs the correct namespace from another API result. That should fix it.

**Comment by Revadike** [comment]
https://github.com/Revadike/epicgames-freebies-claimer/releases/tag/V1.5.8

**Comment by jackblk** [comment]
For Docker users, building here: https://github.com/jackblk/EFC-Docker-Image/actions/runs/1596868633

**Comment by antoinerzad1** [comment]
Hello i got a problem with the new version 
![image](https://user-images.githubusercontent.com/40497631/146655612-0d732065-b5ce-4b44-a9bf-9c41dc1d0142.png)
He say already claimed but the game are not claim

**Comment by jackblk** [comment]
@antoinerzad1 @Revadike I have the same problem. I created a new ticket here https://github.com/Revadike/epicgames-freebies-claimer/issues/172

I think it's a bug from `epicgames-client`, not from EFC.
