### ISSUE TITLE
How setup apprise?

### ISSUE THREAD

**Issue by ExLimeEl** [Revadike/epicgames-freebies-claimer#168]
ERROR | Failed to send push notification (ERROR: Maybe apprise not found?)

As if everything is set up correctly

**Comment by solomonricky** [comment]
Take a look #158

**Comment by jackblk** [comment]
If you use Docker then you probably don't need to do anything.

But for normal user, you need to install Apprise with Python. Let me update the wiki on configuring Apprise, but for now you can do this:

* Install Python >= 3.8
* `pip install apprise`

Then you can use apprise for notification now.

**Comment by Revadike** [comment]
You really need python for it? Kinda sucks you need two different code environments.

**Comment by jackblk** [comment]
Yeah, because Apprise is a Python app. That's why we use docker image, no need to install anything except for docker.
