### ISSUE TITLE
Epic Games enabling 2fa on all free games

### ISSUE THREAD

**Issue by xYosemite** [Revadike/epicgames-freebies-claimer#17]
Epic Games has just announced, around 15 minutes ago, on Twitter that 2fa will be required to claim free games from May 21. They claim that it's for "account security" but it's pretty clear it's for scripts. I am guessing this will render the script obsolete or do you guys think that there could be a work-around?

source: https://www.epicgames.com/store/en-US/news/two-factor-authentication-required-when-claiming-free-games?sessionInvalidated=true

**Comment by Teenari** [comment]
bruh this repo caused it

**Comment by Revadike** [comment]
> bruh this repo caused it

I doubt that. Perhaps somebody with a massive botnet using this library caused it.

**Comment by Teenari** [comment]
> I doubt that. Perhaps somebody with a massive botnet using this library caused it.

well still happened because of this

**Comment by OnigiriFest** [comment]
I've been reading the two-step authentication methods. You can use an email so I don't think I know much of a problem, you can probably read the email by modifying a script, if someone feels like it.

**Comment by OnigiriFest** [comment]
i'm going to try something tomorrow

**Comment by lupohan44** [comment]
> i'm going to try something tomorrow

or you can simply use 2fa code

**Comment by lupohan44** [comment]
> i'm going to try something tomorrow

https://www.npmjs.com/package/node-2fa

**Comment by ProximalPod** [comment]
Hell, maybe it'll trigger less captchas this way haha. I run it once a week and it still doesn't work sometimes because of the captchas

**Comment by xYosemite** [comment]
I don't know node but I am still very interested in seeing if this project finds a way to bypass this or if anyone else does. The node-2fa package seems a little viable? Considering it'll work for Google Authenticator and Epic Games' 2fa [accepts ](https://epicgames.helpshift.com/a/epic-accounts/?s=epic-accounts&f=what-is-two-factor-authentication-2fa-and-how-do-i-opt-in) it. 

update: Just read that it also accepts email like @OnigiriFest has said, could work if a script is made to read any emails by Epic

**Comment by lupohan44** [comment]
> I don't know node but I am still very interested in seeing if this project finds a way to bypass this or if anyone else does. The node-2fa package seems a little viable? Considering it'll work for Google Authenticator and Epic Games' 2fa [accepts ](https://epicgames.helpshift.com/a/epic-accounts/?s=epic-accounts&f=what-is-two-factor-authentication-2fa-and-how-do-i-opt-in) it.
> 
> update: Just read that it also accepts email like @OnigiriFest has said, could work if a script is made to read any emails by Epic

but you don't know what email we are using

**Comment by Revadike** [comment]
Well, the library I use already supports 2fa: https://epicgames-client.kysune.me/Client.html#enabletwofactor-type-twofactorcode

**Comment by lupohan44** [comment]
> Well, the library I use already supports 2fa: https://epicgames-client.kysune.me/Client.html#enabletwofactor-type-twofactorcode

then problem solved

**Comment by capito27** [comment]
btw, @Revadike, about a month ago or so, I implemented OTP support on your script (i couldn't be bothered to push it to my repo). 
If you want to have a look at it, feel free :
https://github.com/capito27/epicgames-freebies-claimer/commit/ff10710488ecf732e362749c50dc48a2bddfe104
now, to update my script to upstream for it to work again

**Comment by lingsamuel** [comment]
PR: https://github.com/Revadike/epicgames-freebies-claimer/pull/19
2FA Secret can be found in the QR-code page when you are enabling 2FA. If you already enabled 2FA, disable and re-enable it, a new secret will be generated and display.

**Comment by Revadike** [comment]
Wanted to close this, but actually, I'll leave it open, as there is still some things to do:
 * Fully test the purchase flow with 2fa
 * Update readme with 2fa secret obtaining method
 * More testing in general

**Comment by chaoscreater** [comment]
Following lingsamuel's instructions, I disabled 2FA and re-enabled it and got the 2FA secret. Added it to my config and tried. All the script did was login to my account and logged out. It wasn't able to claim GTA5 (which requires 2FA).

**Comment by Revadike** [comment]
> Following lingsamuel's instructions, I disabled 2FA and re-enabled it and got the 2FA secret. Added it to my config and tried. All the script did was login to my account and logged out. It wasn't able to claim GTA5 (which requires 2FA).
> 
> > 2020-05-15 | 13:22:21.535 | WARN  | Failed to claim Grand Theft Auto V (Error: Unknown quick purchase status: false)

That's related to https://github.com/Revadike/epicgames-freebies-claimer/issues/22

**Comment by Revadike** [comment]
This is no longer relevant since it uses device auths now
