### ISSUE TITLE
how to run "npm install"

### ISSUE THREAD

**Issue by filipmoco** [Revadike/epicgames-freebies-claimer#176]
How to run npm install

**Comment by Revadike** [comment]
Does this help?
https://github.com/Revadike/epicgames-freebies-claimer/wiki/Installing-EpicGames-Freebies-Claimer

**Comment by filipmoco** [comment]
> Does this help? https://github.com/Revadike/epicgames-freebies-claimer/wiki/Installing-EpicGames-Freebies-Claimer

Yes thanks
