### ISSUE TITLE
How to claim a specific game?

### ISSUE THREAD

**Issue by danYb112** [Revadike/epicgames-freebies-claimer#190]
Hello, how can i claim a specific game only using your program? for example Rocket League.

**Comment by adi170-alt** [comment]
I don't think that is possible yet, but I am obviously not sure

**Comment by Revadike** [comment]
This should still work: https://epicgames-client.kysune.me/Client.html#quickpurchase-offer-quantity
Or, using follow my example: 
https://github.com/Revadike/epicgames-freebies-claimer/blob/c5c1d0a1cea3489538667d691112d9f9940a1d64/src/offerPurchase.js

It is planned to support claiming free games (aside from weekly giveaway), DLC and free assets in the future:
https://github.com/Revadike/epicgames-freebies-claimer/issues/101
https://github.com/Revadike/epicgames-freebies-claimer/issues/73
https://github.com/Revadike/epicgames-freebies-claimer/issues/30
