### ISSUE TITLE
(Error: We could not confirm your purchase at this time.  Please try again later.)

### ISSUE THREAD

**Issue by PattyXD** [Revadike/epicgames-freebies-claimer#195]
### Expected Behavior
I expect it to claim some games

### Actual Behavior
it dont claim and give me error: (Error: We could not confirm your purchase at this time.  Please try again later.)

### Steps to Reproduce the Problem

  1. Using Github actions

### Specifications

  - `epicgames-freebies-claimer` Version: 1.5.8
  - Platform / OS: idk
  - Node Version: idk

**Comment by Revadike** [comment]
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/172
