### ISSUE TITLE
Error: We could not confirm your purchase at this time.  Please try again later.

### ISSUE THREAD

**Issue by ProBlacKirito** [Revadike/epicgames-freebies-claimer#196]
![Immagine 2022-03-19 160205](https://user-images.githubusercontent.com/74011684/159126404-29937827-3060-4f38-b337-9664be1725f4.png)

**Comment by Revadike** [comment]
Please check the pinned issue: https://github.com/Revadike/epicgames-freebies-claimer/issues/172
