### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by Alahmaha** [Revadike/epicgames-freebies-claimer#198]
npm : Die Benennung "npm" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren
Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und
wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ npm
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Alahmaha** [comment]
It's show me when I run npm install in power shell.

**Comment by Revadike** [comment]
install node.js
