### ISSUE TITLE
Listen to a feed

### ISSUE THREAD

**Issue by Revadike** [Revadike/epicgames-freebies-claimer#2]
I could make the script listen to a feed that announces new epicgames freebies and automatically claim them afterwards. This would make the whole process fully automated.
Example feeds:
https://getgloss.app/
https://barter.vg/giveaways/json

**Comment by YaBoiAce** [comment]
This would be a really good idea, I installed it on my VPS and this has worked charms so far. A way to automate it would make it amazing.

**Comment by Revadike** [comment]
For now, you will just have to ping, like run a daily cron job.
Actually, [this fork](https://github.com/fer662/epicgames-freebies-claimer) by @fer662 already does this.

**Comment by fer662** [comment]
Hey there. Essentially my fork runs off env vars and runs multiple accounts.  I hosted it on Heroku, the main process just opens a dummy socket so Heroku won't think it's dead, and then it runs the singlecheck.js script with a "cron job" (it's an add on, I don't remember the name). All free.

**Comment by YaBoiAce** [comment]
I installed yours on to my VPS via a screen thinking it would just run automatically every now and then but it closes after a while.

Just attempted Heroku but it's mad confusing, do you have any guide for it? I've connected my fork of it but it's running the index.js not the singlecheck.js; It's not allowing me to change it.

**Comment by Revadike** [comment]
> I installed yours on to my VPS via a screen thinking it would just run automatically every now and then but it closes after a while.
> 
> Just attempted Heroku but it's mad confusing, do you have any guide for it? I've connected my fork of it but it's running the index.js not the singlecheck.js; It's not allowing me to change it.

Are you using his fork, or mine? Be sure to use @fer662's fork

**Comment by YaBoiAce** [comment]
> > I installed yours on to my VPS via a screen thinking it would just run automatically every now and then but it closes after a while.
> > Just attempted Heroku but it's mad confusing, do you have any guide for it? I've connected my fork of it but it's running the index.js not the singlecheck.js; It's not allowing me to change it.
> 
> Are you using his fork, or mine? Be sure to use @fer662's fork

Yes, I am. Heroku is being annoying and running @fer662's index.js file, not singlecheck.js file; can't seem a way to change it. Frustrating but should be pretty easy to find I suppose haha

**Comment by Revadike** [comment]
> Heroku is being annoying and running @fer662's index.js file, not singlecheck.js file

My guess would be they're reading package.json, which indicates `"main": "index.js",`. This should be fixed.

**Comment by YaBoiAce** [comment]
> > Heroku is being annoying and running @fer662's index.js file, not singlecheck.js file
> 
> My guess would be they're reading package.json, which indicates `"main": "index.js",`. This should be fixed.

Went ahead and forked it, changed the package.json and re-installed the app. Still running the `index.js` for some odd reason. Looks like I'll just have to figure out how to make Heroku manually run `singlecheck.js`

**Comment by YaBoiAce** [comment]
> Hey there. Essentially my fork runs off env vars and runs multiple accounts. I hosted it on Heroku, the main process just opens a dummy socket so Heroku won't think it's dead, and then it runs the singlecheck.js script with a "cron job" (it's an add on, I don't remember the name, edit: "Advanced Scheduler"). All free.

Thank you! Figured out how to make it automated via your method; just took a lot of trial-and-error .

**Comment by Revadike** [comment]
Unless there was a way to directly listen to a direct epicgames feed or websocket for new free games announcement, we may as well just ping instead by looping the script, which was already implemented in https://github.com/Revadike/epicgames-freebies-claimer/commit/b7468b11da8d9303bfb74babafb00196f286562e
