### ISSUE TITLE
Is this an error? "2022-11-05 | 09:39:43.954 | ERROR | TypeError: Cannot read properties of undefined (reading 'id')"

### ISSUE THREAD

**Issue by CokeVoAYCE** [Revadike/epicgames-freebies-claimer#203]
### Details
![error running with powershell](https://user-images.githubusercontent.com/59302755/200125366-dd19434e-9bfc-4953-989d-02acc4a34f32.jpg)

### Background (if needed)
I already claimed the first game manually before looking for an automated way to do it and using this. Is this error caused because I already claimed the game, or is this something else? I've run the device auths code from the other program and already put it in the freebees claimer data folder, so if it is an issue with the authentication, I'm not sure why. Everything should be up to date, just installed and attempted to use them both today as of 11/5/2022, and got the latest versions and pip installed and npm installed everything. Thoughts/ideas?

**Comment by Revadike** [comment]
https://github.com/Revadike/epicgames-freebies-claimer#%EF%B8%8Fstatus%EF%B8%8F
