### ISSUE TITLE
[DOCS] Add minimum Node version (`v15.0.0`) in the README

### ISSUE THREAD

**Issue by LukeSavefrogs** [Revadike/epicgames-freebies-claimer#204]
## Problem
When running `node epic games` I get the following error:
```
→ D:\Progetti\free-games-claimer [main ≡]› node epic-games
file:///D:/Progetti/free-games-claimer/epic-games.js:20
db.data ||= {};
        ^^^

SyntaxError: Unexpected token '||='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
    at async link (internal/modules/esm/module_job.js:63:21)
```

This is because, as stated by [the docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment#browser_compatibility) the `||=` operator is supported from NodeJS >= 15.0.0.
After a quick check, it appears on my system i have not this requirement:
```
→ D:\Progetti\free-games-claimer [main ≡]› node --version
v14.17.1
```

## Solution
Add a disclaimer in the README or in the wiki that you MUST install Node >= 15.

**Comment by gogoiakash2311** [comment]
Hey @LukeSavefrogs  Can you assign this to me

**Comment by LukeSavefrogs** [comment]
> Hey @LukeSavefrogs Can you assign this to me

I don't have the permission.

**Comment by gogoiakash2311** [comment]
![Screenshot 2022-11-21 at 1 46 06 PM](https://user-images.githubusercontent.com/91525166/202998754-ea4f6a96-1a6c-4db6-b410-e9854744ed87.png)

@LukeSavefrogs @Revadike Is it okay??

**Comment by LukeSavefrogs** [comment]
> ![Screenshot 2022-11-21 at 1 46 06 PM](https://user-images.githubusercontent.com/91525166/202998754-ea4f6a96-1a6c-4db6-b410-e9854744ed87.png)
> 
> @LukeSavefrogs @Revadike Is it okay??
> 

Thank you 😄

**Comment by LukeSavefrogs** [comment]
> ![Screenshot 2022-11-21 at 1 46 06 PM](https://user-images.githubusercontent.com/91525166/202998754-ea4f6a96-1a6c-4db6-b410-e9854744ed87.png)
> 
> @LukeSavefrogs @Revadike Is it okay??
> 

Thank you 😄

**Comment by gogoiakash2311** [comment]
Okay then I'll make PR
