### ISSUE TITLE
Null error

### ISSUE THREAD

**Issue by 1uckd** [Revadike/epicgames-freebies-claimer#207]
![image](https://user-images.githubusercontent.com/121422748/209519417-fe41c8a9-6b6f-4111-bc98-642c6c09152d.png)

### Specifications

  - `epicgames-freebies-claimer` Version: 1.5.8
  - Platform / OS: win 10
  - Node Version: lastest

**Comment by SteveImmanuel** [comment]
Also happened on my system, ran on docker.
This error is most likely came from this line,
```
let purchased = await client.purchase(offer, 1);
```
which is why the error log is `null`

**Comment by Shelvak** [comment]
Same here, I removed node_modules/ , install again, recreate the token after the "child policy".... nothing fix the `error: null`

**Comment by Revadike** [comment]
https://github.com/Revadike/epicgames-freebies-claimer/issues/172
