### ISSUE TITLE
Use a Captcha Solver like 2chaptcha

### ISSUE THREAD

**Issue by GamesReborn** [Revadike/epicgames-freebies-claimer#210]
To by pass the captcha's why not use a captcha solver. We would have to pay of course but about 1k captcha's is $3 so that's atleast min 100 games

**Comment by Revadike** [comment]
The captcha isn't the issue. It's the custom fingerprinting bs they've added to the hcaptcha verification.

**Comment by Revadike** [comment]
Read more here:
https://github.com/Revadike/epicgames-freebies-claimer/pull/184#issuecomment-1039539642

**Comment by eebssk1** [comment]
I'm using paid Captcha Solver, but only works very a few times.It looks like Talon Services is intelligent enough to block both bots and legitimate user.
