### ISSUE TITLE
A couple of questions/issues...

### ISSUE THREAD

**Issue by chaoscreater** [Revadike/epicgames-freebies-claimer#23]
Hi,

I haven't updated my version for a while and thought I'd come here to see whether there has been any updates. I'm currently 3 versions behind. Looking at the changelog, it looks like it now supports looping (run forever). How does this work exactly? If I restart my PC, how will it continue to run in the background? 

My current configuration is to have a scheduled task to run the script at a specific time everyday. As scheduled task is a built-in feature for Windows, it'll just work. However, I'm unsure how this looping works for your script. Surely if the machine is restarted, the script has to be triggered by something to run again? It's not running as a Windows service and doesn't run at machine startup or as a task....

More importantly, I have an issue running the script against multiple accounts. I've always just been using 1 account, but now I would like to run this against 3 accounts. My config looks like this:

```

{
	"accounts": [
		{
			"email": "blah@gmail.com",
			"password": "asfdsfdsfsdfsd",
			"secret": "YOUR_2FA_SECRET1_HERE_OR_EMPTY",
			"rememberLastSession": true
		},
		{
			"email": "blah2@gmail.com",
			"password": "asfdsfdsfsdfsd",
			"secret": "YOUR_2FA_SECRET2_HERE_OR_EMPTY",
			"rememberLastSession": true
		},
		{
			"email": "blah3@gmail.com",
			"password": "asfdsfdsfsdfsd",
			"secret": "YOUR_2FA_SECRET2_HERE_OR_EMPTY",
			"rememberLastSession": true
		}				
	],
	"delay": 1440,
	"loop": false
}
```

The problem is, only the first account is used to claim the games. I'm not sure what I'm doing wrong here. I think someone mentioned the same thing in one of the logged issues.

Last issue I'm experiencing is that I'm getting this message for all my accounts:

> Failed to login as blah@gmail.com, please attempt manually.

It will then open a Chrome window and log me in automatically. So that would suggest my config is correct. The script doesn't seem to login automatically or remember the last session anymore, it will always show that Chrome window...

**Comment by Revadike** [comment]
The looping function requires the script to be running 24/7. You can set the delay between each check.
About the multiaccount issue, I'm suspecting `rememberLastSession` may only support 1 account. Can you test this? Next time, please make a 1 issue for each seperate problem/question, this will be better for the issue-tracker.

**Comment by chaoscreater** [comment]
I've tested it and yes you're right, that seems to be the case here. I guess I would need to clone the project folder and have 1 account per config file?

The reason why I'm using **rememberLastSession** is because prior to the policy changes that Epic has made, you only needed to sign into the account and enter the 2FA code just once and you wouldn't have to do that again (assuming rememberLastSession is used). I don't know whether rememberLastSession is still useful now or not.

**Comment by Revadike** [comment]
I added multiaccount support for my fork, which is now being used for the library. Please update and check if the issue is solved.
