### ISSUE TITLE
I cant start the program

### ISSUE THREAD

**Issue by antoinerzad** [Revadike/epicgames-freebies-claimer#25]
Hello i cant start the program can you help me
i have this error

 epicgames-freebies-claimer@1.4.0 start /home/pi/epicgames-freebies-claimer
> node claimer.js "antoinerzad2@gmail.com" "password" "0"

internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module 'check-update-github'
Require stack:
- /home/pi/epicgames-freebies-claimer/claimer.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/pi/epicgames-freebies-claimer/claimer.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js                                                                                                                     :71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/epicgames-freebies-claimer/claimer.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epicgames-freebies-claimer@1.4.0 start: `node claimer.js "antoinerzad2@                                                                                                                     gmail.com" "password" "0"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epicgames-freebies-claimer@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                     ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-05-15T13_37_41_731Z-debug.log

**Comment by Revadike** [comment]
`npm install`

**Comment by secu2** [comment]
The dependency is missing for me in the package.json, the npm install didn't work, i added it manually to make it work
#26

**Comment by antoinerzad** [comment]
Thank you for your help
Now I have a new mistake I have a mistake with the chrome I think it's not installed

>  2020-05-16 | 09:53:00.253 | WARN  | Failed to login as YOUR_EMAIL1_HERE, please attempt manually.
 2020-05-16 | 09:53:01.566 | ERROR | Error: Failed to launch the browser process!
/home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 1: /home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: �: not found
/home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 1: /home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome:ELF: not found
/home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 2: /home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: p#: not found
/home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 3: /home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: p#: not found
/home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 4: /home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: @l�: not found
/home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 4: /home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: /home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 5: /home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: ��q: not foundpX: not found

/home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 6: /home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: pX: not found
/home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 7: /home/pi/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: Syntax error: "(" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/pi/epicgames-freebies-claimer/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.<anonymous> (/home/pi/epicgames-freebies-claimer/node_modules/puppeteer/lib/Launcher.js:739:50)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1225:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epicgames-freebies-claimer@1.4.0 start: `node claimer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epicgames-freebies-claimer@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

![image](https://user-images.githubusercontent.com/24781761/82114178-67f2b980-975b-11ea-9ee2-c92a932cfd4b.png)

**Comment by alexandervnuchkov** [comment]
> Thank you for your help
> Now I have a new mistake I have a mistake with the chrome I think it's not installed

That is due to the fact, that npm downloads the chrome version that is not compatible with your RPi (as far as I can see you are using Raspberry Pi). I had the same problem, it's actually the `puppeteer` issue, not the claimer. I did the following:
- opened the `node_modules/epicgames-client-login-adapter/index.js` file;
- found the `const browser = await Puppeteer.launch({});` line (it's line 40 in my file);
- add the `executablePath: 'chromium-browser',` line between the `headless: false,` and `defaultViewport: {},`.
After that the script works as intended.

**Comment by antoinerzad** [comment]
thanks you 

> > Thank you for your help
> > Now I have a new mistake I have a mistake with the chrome I think it's not installed
> 
> That is due to the fact, that npm downloads the chrome version that is not compatible with your RPi (as far as I can see you are using Raspberry Pi). I had the same problem, it's actually the `puppeteer` issue, not the claimer. I did the following:
> 
> * opened the `node_modules/epicgames-client-login-adapter/index.js` file;
> * found the `const browser = await Puppeteer.launch({});` line (it's line 40 in my file);
> * add the `executablePath: 'chromium-browser',` line between the `headless: false,` and `defaultViewport: {},`.
>   After that the script works as intended.

Thanks you !
Now i have a new issue

i have this 
> node claimer.js

 2020-05-16 | 10:35:39.488 | WARN  | Failed to login as YOUR_EMAIL1_HERE, please attempt manually.
 2020-05-16 | 10:35:41.216 | ERROR | Error: Failed to launch the browser process!
[1384:1384:0516/103540.680065:ERROR:browser_main_loop.cc(584)] Failed to put Xlib into threaded mode.

(chromium-browser-v7:1384): Gtk-WARNING **: 10:35:41.113: cannot open display:


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/pi/epicgames-freebies-claimer/node_modules/puppeteer/lib/Launcher.js:750:14)
    at ChildProcess.<anonymous> (/home/pi/epicgames-freebies-claimer/node_modules/puppeteer/lib/Launcher.js:740:61)
    at ChildProcess.emit (events.js:327:22)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epicgames-freebies-claimer@1.4.0 start: `node claimer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epicgames-freebies-claimer@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-05-16T08_35_41_305Z-debug.log


![image](https://user-images.githubusercontent.com/24781761/82115124-2f55de80-9761-11ea-95d8-df0d01da277b.png)

its normal ?

**Comment by antoinerzad** [comment]
Ok I think I know where the error came from I guess I need to run the program in a vncserver.

**Comment by antoinerzad** [comment]
thanks you for the help !

**Comment by antoinerzad** [comment]
![image](https://user-images.githubusercontent.com/24781761/82115250-e05c7900-9761-11ea-9652-20b6e0cbf24b.png)

**Comment by antoinerzad** [comment]
The program try every day to claim new game ?
