### ISSUE TITLE
Always fails to automatically login

### ISSUE THREAD

**Issue by maximousblk** [Revadike/epicgames-freebies-claimer#29]
![image](https://user-images.githubusercontent.com/28438021/82082655-081df380-9706-11ea-9254-7eb2759816f0.png)

Why does this happen? This can also be a problem in #27

**Comment by xCuri0** [comment]
I have the same issue but can't manually login because I'm running this on a server

**Comment by Revadike** [comment]
> I have the same issue but can't manually login because I'm running this on a server

Do you have the latest version?

**Comment by xCuri0** [comment]
@Revadike cloned it a few hours ago so yes

**Comment by cazzoo** [comment]
I having the same issue...

**Comment by SergioSV96** [comment]
I am having the same issue too.

` 2020-06-04 | 17:57:14.655 | INFO  | Logged in as --------(--------)
 2020-06-04 | 17:57:19.859 | WARN  | Failed to claim Overcooked (Error: Unknown quick purchase status: false)
 2020-06-04 | 17:57:24.196 | INFO  | Logged -------- out of Epic Games
`

**Comment by maximousblk** [comment]
@SergioSV96 you are looking for #22

**Comment by davispuh** [comment]
Most likely this is same as #42

**Comment by Revadike** [comment]
This is no longer relevant since it uses device auths now
