### ISSUE TITLE
Please help. I have no idea what i'm doing.

### ISSUE THREAD

**Issue by Proppern** [Revadike/epicgames-freebies-claimer#34]
No idea why it doesn't work. I have installed node.js with additional build tools option installed.

![error](https://user-images.githubusercontent.com/51683203/83600357-9b757680-a598-11ea-8eb6-c0a1ac14edbc.png)

[2020-06-03T05_38_58_956Z-debug.log](https://github.com/Revadike/epicgames-freebies-claimer/files/4721256/2020-06-03T05_38_58_956Z-debug.log)

**Comment by Revadike** [comment]
run `npm install` first

**Comment by Proppern** [comment]
i did npm install but then it said this 
![error 2](https://user-images.githubusercontent.com/51683203/83938104-07a3e480-a7fc-11ea-8e88-4723b4193ab0.png)

**Comment by Revadike** [comment]
That's it. It should work now.

**Comment by Proppern** [comment]
i used npm start * and now it's showing this.
![error 3](https://user-images.githubusercontent.com/51683203/83987665-37252f00-a96b-11ea-8f39-de3510f31fd0.png)

[2020-06-08T02_27_19_382Z-debug.log](https://github.com/Revadike/epicgames-freebies-claimer/files/4743585/2020-06-08T02_27_19_382Z-debug.log)

**Comment by Dareeo** [comment]
Type in just `npm start`

**Comment by Proppern** [comment]
still error...

![error 4](https://user-images.githubusercontent.com/51683203/84467377-298ee280-aca6-11ea-9f7d-4303a2328a5b.png)

**Comment by Proppern** [comment]
still error

![error 4](https://user-images.githubusercontent.com/51683203/84467764-4841a900-aca7-11ea-82d5-867373ab3f94.png)

**Comment by Revadike** [comment]
Make sure you run `npm install` in the same folder you run `npm start`. If it still doesn't work, make sure you are on the latest version and try this: `npm unsintall` then `npm install`.
