### ISSUE TITLE
2FA - remember device?

### ISSUE THREAD

**Issue by chaoscreater** [Revadike/epicgames-freebies-claimer#4]
Hi there!

First of all, thanks for making this! It definitely makes it easy for lazy people like me to claim the free games on a weekly basis. I've missed claiming games a few times, so this definitely helps!

Anyway, I've tried this and it works well. But it always prompts me to enter the 2FA code. It shouldn't do that, because in a normal browser session, it will remember your device and shouldn't prompt you every single time you access the website. Could you please update the app to support remembering the device?

**Comment by Revadike** [comment]
`epicgames-client@2.0.23` released!
- Added possibility to login with exchange code. Read more here: https://epicgames-client.kysune.me/Client.html#login-options-exchangecode
- Added remembering last session. To enable it please set client's option `rememberLastSession` to `true` (defaults disabled). Please be careful to this option while you're using `epicgames-client` with multiple accounts in one script.

**Comment by chaoscreater** [comment]
OK, I did a bit of Google search and found this:

> npm install -g npm-install-peers

I opened powershell in the same folder as the project folder and ran the command above. No errors, seems to be all good. Then when I tried to run **node gimme_free_epic_shit**, it shows this:

> Error: Error while initializing or logging in as blah@gmail.com
>     at E:\Downloads\Games\epicgames-freebies-claimer-master\gimme_free_epic_shit.js:10:15
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Revadike** [comment]
To update dependencies, simply run `npm update` in the same way you ran `npm install`.
Also, I'm about to release a small update to the project that enables `rememberLastSession` by default.

**Comment by chaoscreater** [comment]
Have downloaded the updated file in Release, did a "npm install -g npm-install-peers" and that went OK. Then I also did a npm update and no updates were found it seems. Tried running and I'm still getting the same "captcha_invalid" issue.


![image](https://user-images.githubusercontent.com/18227319/78617284-0113f200-78cb-11ea-84ed-08988d8961b5.png)

**Comment by Revadike** [comment]
> npm-install-peers

I don't have any `peerDependencies`, so this was not needed. Only `npm update` was needed.
There's still no real fix for captcha, now it just remembers your login. 
For the captcha issue, please use https://github.com/Revadike/epicgames-freebies-claimer/issues/3

**Comment by chaoscreater** [comment]
Thanks. Looks like using a VPN worked. I guess I was trying to login so many times that Epic probably got suspicious at the logon attempts coming from the same IP address.

I can confirm that it's not asking for the 2FA code anymore now that I'm using the latest release. This is great, thanks heaps.

**Comment by MusTangLee** [comment]
> To update dependencies, simply run `npm update` in the same way you ran `npm install`.
> Also, I'm about to release a small update to the project that enables `rememberLastSession` by default.

Could you add rememberLastSession to the config and process.argv ?
Would make batch running the script (for tests and self use) on about 10 accounts much easier.

**Comment by Revadike** [comment]
> > To update dependencies, simply run `npm update` in the same way you ran `npm install`.
> > Also, I'm about to release a small update to the project that enables `rememberLastSession` by default.
> 
> Could you add rememberLastSession to the config and process.argv ?
> Would make batch running the script (for tests and self use) on about 10 accounts much easier.

It sets `rememberLastSession` to `true` for all methods, commandline/config/etc

**Comment by MusTangLee** [comment]
> > > To update dependencies, simply run `npm update` in the same way you ran `npm install`.
> > > Also, I'm about to release a small update to the project that enables `rememberLastSession` by default.
> > 
> > 
> > Could you add rememberLastSession to the config and process.argv ?
> > Would make batch running the script (for tests and self use) on about 10 accounts much easier.
> 
> It sets `rememberLastSession` to `true` for all methods, commandline/config/etc

I know, that's the problem.
You can't run the script on multiple accounts when rememberLastSession is set to true hardcoded.
I'm asking to ADD it to process.argv and config to be able to change it.
I want to be able to do
node gimme_free_epic_shit username1 password false
node gimme_free_epic_shit username2 password false
node gimme_free_epic_shit username3 password false
etc.

Currently when I run the commandline on multiple accounts it always logs in as the FIRST account over and over.

**Comment by Revadike** [comment]
Ah, I didn't know this. Would you mind creating a separate issue about this?

**Comment by MusTangLee** [comment]
> Ah, I didn't know this. Would you mind creating a separate issue about this?

#8 

done.
