### ISSUE TITLE
 Permission denied (publickey)

### ISSUE THREAD

**Issue by Scarface2k14** [Revadike/epicgames-freebies-claimer#41]
Hey there,

for some reason I'm not able to download the dependency: node-epicgames-client
Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-github-revadike-node-epicgames-client-a179948a'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Tested on v1.4.1.
Any suggestions?

**Comment by Revadike** [comment]
Try now

**Comment by Scarface2k14** [comment]
still the same error..

**Comment by Revadike** [comment]
Make sure you have the latest version of git installed
