### ISSUE TITLE
Fails to automatically login due to captcha

### ISSUE THREAD

**Issue by gab** [Revadike/epicgames-freebies-claimer#42]
I systematically get `Failed to login as [username], please attempt manually.`

(Logging in through the browser that opens afterwards works, though it only types in the username + password, and fails to auto-type the 2FA code despite it being generated correctly in the code, which I debugged.)

I've logged the error that comes from the node-epicgames-client, and it says the following:
`Error: Unknown auth error: errors.com.epicgames.accountportal.captcha_invalid`
I suspect that the Epic website is somehow detecting that we're not a real browser, either through the lack of cookies, just the user agent string or some advanced javascript magic, and adding an extra challenge. The captcha doesn't show up in the subsequent pupetteer browser that opens.

This is the change I did to log the error btw. No time at the moment for a proper pull request, sorry:
```
diff --git a/claimer.js b/claimer.js
index 8da7716..7db0e30 100644
--- a/claimer.js
+++ b/claimer.js
@@ -73,8 +73,12 @@ async function freeGamesPromotions(client, country = "US", allowCountries = "US"
                 throw new Error("Error while initialize process.");
             }

-            if (!await client.login(account).catch(() => false)) {
-                Logger.warn(`Failed to login as ${client.config.email}, please attempt manually.`);
+            if (!await client.login(account).catch(error =>
+                {
+                    Logger.warn(`Failed to login as ${client.config.email} with error ${error}, please attempt manually.`);
+                    return false;
+                }))
+                {

                 let auth = await ClientLoginAdapter.init(account);
                 let exchangeCode = await auth.getExchangeCode();
```
Resulting output:
`Failed to login as [username] with error Error: Unknown auth error: errors.com.epicgames.accountportal.captcha_invalid, please attempt manually.`

**Comment by Revadike** [comment]
And it didn't prompt the captcha in the browser? That's weird. I suggest you move this issue to the library that's responsible for this part: https://github.com/SzymonLisowiec/node-epicgames-client-login-adapter/issues

**Comment by gab** [comment]
Whether a captcha is presented might be related to whether you're connecting to their server through a VPN and/or to the frequency of connection tries, because I just tried again and both the automatic login and the attempt to claim Torchlight II (was already claimed) passed without error.

However right after, I closed and restarted the program and got this:
`WARN  | Failed to claim Torchlight II (Error: errors.com.epicgames.purchase.purchase.captcha.challenge)`

And nope, no browser opens for the captcha on login or the captcha on "purchase" (weird that it even attempts to purchase BTW since you can see on the game's page whether you own it without adding it to cart - is that from your script or from upstream?). I'm not sure it's worth taking this up upstream to SzymonLisowiec since you said he's not maintaining this stuff anymore?

**Comment by Revadike** [comment]
He said he would take a look at the purchase flow months ago, but he hasn't had the time since.

**Comment by davispuh** [comment]
Same issue here. It always fails with `Unknown auth error: errors.com.epicgames.accountportal.captcha_invalid`
Manual login with browser works fine. But I shouldn't have to do that every time.
I've set `"rememberLastSession": true` and I see that `lastSessionCookies.json` is created with cookies.

Only cookies that change between different runs are `EPIC_SESSION_AP` and `EPIC_SESSION_REPUTATION`

**Comment by Qdelta** [comment]
Yeah, I'm getting the same issue and it doesn't even allow enough time to fill in the Captcha.
This bug kind of makes this script irrelevant since I want to set and forget this script... not maintain it.

**Comment by Revadike** [comment]
This is no longer relevant since it uses device auths now
