### ISSUE TITLE
npm ERR ENOENT

### ISSUE THREAD

**Issue by spabaex** [Revadike/epicgames-freebies-claimer#44]
I have installed node.js,download your repo, but it's don't work. I tried `"mkdir .egstore"`, but it doesn't help :( How can I fix it? Thank you ❤
![image](https://user-images.githubusercontent.com/68686778/88269715-98b81780-cce5-11ea-8033-3ca8c4fe022c.png)

**Comment by ZD4ve** [comment]
I have the same problem, somebody please help!

**Comment by loveqianool** [comment]
install git
