### ISSUE TITLE
WARN  | Failed to claim TITLE(Error: Unable to acquire purchase token)

### ISSUE THREAD

**Issue by vexersa** [Revadike/epicgames-freebies-claimer#46]
I'm not sure what is causing this but getting the error: 
WARN  | Failed to claim GAME TITLE HERE (Error: Unable to acquire purchase token)

**Comment by davispuh** [comment]
Same here aswell. Maybe because I got that game manually myself with browser?

**Comment by vexersa** [comment]
Could be, though I never claimed the game as I wanted to verify that the
claimer was working.

**Comment by Th3irdEye** [comment]
I have the same issue. Just getting the "Unable to acquire purchase token" error every time I run it. I have not claimed any of the currently available free games.

**Comment by Revadike** [comment]
Can you verify if it's fixed? Closing this in the meanwhile...
