### ISSUE TITLE
Says x is already claimed, yet it isn't?

### ISSUE THREAD

**Issue by xYosemite** [Revadike/epicgames-freebies-claimer#5]
Hi, ran the script today because Epic has released "Close to the sun" and "Sherlock Holmes Crimes and Punishments" and the output says:
`Logged in as x (x)`
`Close to the Sun was already claimed for this account`
`Sherlock Holmes Crimes and Punishments was already claimed for this account`
`Lego Batman Trilogy was already claimed for this account`
`Logged out of Epic Games`

ignore x, that's just my info.
It says these games are already claimed, yet they're not in my library. I've not run the script before today. I believe it could be something to do with regions or something? I'm in the UK and my Epic Games account is based in the UK; there is no "Lego Batman Trilogy" on the free games tab on my epic either. 

edit: I think it could also be something to do with this? 
![image](https://user-images.githubusercontent.com/22438504/78927209-61a35a80-7a96-11ea-8e9a-cd2502640e0c.png)
Maybe this is canceling the script out making it believe it's already claimed? 

Thanks.

**Comment by BahMike** [comment]
I also have this problem, though it looks to be a problem on epic-client's (the library Revadike uses) end

**Comment by YaBoiAce** [comment]
Ah, that sucks. Guess there's nothing we can do except wait.

**Comment by crsleeth** [comment]
Mine successfully claimed Close to the Sun and Sherlock Holmes but also gives the incorrect line "Lego Batman Trilogy was already claimed for this account".

**Comment by YaBoiAce** [comment]
> Mine successfully claimed Close to the Sun and Sherlock Holmes but also gives the incorrect line "Lego Batman Trilogy was already claimed for this account".

Was just about to post this, I got this too a few hours ago.

**Comment by rheasbelt** [comment]
I played with it a bit and found out that setting your country in profile matching the ip address you're trying to claim games from helps. So in case you have your script installed on a machine located in Netherlands, you have to set it to the same country in Epic Games profile, then it will run successfully. Hope it helps.

**Comment by rheasbelt** [comment]
I played with it a bit and found out that setting your country in profile matching the ip address you're trying to claim games from helps. So in case you have your script installed on a machine located in Netherlands, you have to set it to the same country in Epic Games profile, then it will run successfully. Hope it helps.

Upd: although I see that OP said that both script and their profile are based in the UK, so I'm not sure what could be wrong in that case.

**Comment by lucifudge** [comment]
not working, getting the lego batman error

**Comment by blankws** [comment]
> I played with it a bit and found out that setting your country in profile matching the ip address you're trying to claim games from helps. So in case you have your script installed on a machine located in Netherlands, you have to set it to the same country in Epic Games profile, then it will run successfully. Hope it helps.
> 
> Upd: although I see that OP said that both script and their profile are based in the UK, so I'm not sure what could be wrong in that case.

I just change the country in profile, but still error.

**Comment by crsleeth** [comment]
For what it's worth I have my account country and IP in the same region but still get the error. It can just be ignored though I am still able to claim the other games.

**Comment by Revadike** [comment]
Any idea if this is solved now with V1.3.0?

**Comment by blankws** [comment]
> 2020-04-26 | 23:28:35.184 | WARN  | Failed to login as myemail@xxx.com, please attempt manually.
 2020-04-26 | 23:28:35.203 | ERROR | Error: Failed to launch the browser process!
/root/epicshit/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/root/epicshit/epicgames-freebies-claimer/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.helper.addEventListener (/root/epicshit/epicgames-freebies-claimer/node_modules/puppeteer/lib/Launcher.js:739:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at Socket.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)


I deleted old files,and reinstall, but it display this.

**Comment by Revadike** [comment]
try `npm uninstall`, then `npm install`

**Comment by blankws** [comment]
Still display this:

>  2020-04-26 | 23:41:11.369 | WARN  | Failed to login as myname@gmail.com, please attempt manually.
 2020-04-26 | 23:41:11.408 | ERROR | Error: Failed to launch the browser process!
/root/epicshit/epicgames-freebies-claimer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/root/epicshit/epicgames-freebies-claimer/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.helper.addEventListener (/root/epicshit/epicgames-freebies-claimer/node_modules/puppeteer/lib/Launcher.js:739:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at Socket.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)

**Comment by blankws** [comment]
By the way, when I try `npm install`, it shows `npm WARN xmpp-jid@1.3.0 requires a peer of node-stringprep@^0.8.0 but none was installed.`.

**Comment by Revadike** [comment]
Hmm, maybe try `npm install puppeteer` first? If that doesn't work, I suggest you open an issue [here](https://github.com/puppeteer/puppeteer/issues)

**Comment by lucifudge** [comment]
Well, I had already claimed it, but it's no longer displaying the Batman error. Seems like this was probably fixed!

> 2020-04-26 | 13:39:42.947 | INFO  | For The King was already claimed for this account

Had to run npm and CD to my working directory and _npm uninstall_, then _npm install_ as you suggested.

**Comment by lucifudge** [comment]
Hmm, this is still happening. 
 **2020-04-30 | 13:01:32.564 | INFO  | Amnesia: The Dark Descent was already claimed for this account
 2020-04-30 | 13:01:32.895 | INFO  | Crashlands was already claimed for this account**

Version 1.3.0. Confirmed in my Epic Library that neither of these games are there.

**Comment by Revadike** [comment]
Yes, I made an issue about this here: https://github.com/SzymonLisowiec/node-epicgames-client/issues/87
Weird part is it only happens to some accounts.

**Comment by Revadike** [comment]
Is this issue still present?

**Comment by marchenm** [comment]
Just ran into this issue with v1.5.0.  

> | INFO  | Frostpunk was already claimed for this account

It had an 18+ screen before I could claim it in the app.

**Comment by Revadike** [comment]
> Just ran into this issue with v1.5.0.
> 
> > | INFO  | Frostpunk was already claimed for this account
> 
> It had an 18+ screen before I could claim it in the app.

Thanks for the observation! This may be fixable.

**Comment by Revadike** [comment]
It appears the 18+ prompt is just for accessing the store page.
But I pushed an update to [epicgames-client](https://github.com/Revadike/node-epicgames-client) that should properly detect the error.
So, no more saying x is already claimed, yet it isn't. 

Please, run `npm uninstall epicgames-client & npm install epicgames-client` to update the `epicgames-client` dependency.
