### ISSUE TITLE
Failed to exec start script

### ISSUE THREAD

**Issue by Dareeo** [Revadike/epicgames-freebies-claimer#53]
Hello
I'm trying to run this application, but it fails. I have the latest version on Windows.
I've installed nide.js and git.
Do I need to install EPic lanucher as well?
I tried to put my creds in config file and start it with npc start command (if you need log let me know)
Also I tried to run it on this way:
npc start myusername mypassword 1 my2facode LOG: https://pastebin.pl/view/6c4bf224
npc start myusername mypassword my2facode LOG: https://pastebin.pl/view/3f1e23a8
But it always fails.
I'm running cmd as admin. It seems like it can't create a directory, but idk why.
Please let me know what could be the issue?
Thanks

**Comment by Dareeo** [comment]
fixed with manual directory creation

**Comment by Revadike** [comment]
What directory?

**Comment by Dareeo** [comment]
.egstore

After that I had to extend timeout as I always failed on chapta solving, now I can login, but it log me out with htis error msg:

 2020-08-31 | 14:47:20.872 | WARN  | Failed to login as mymail@gmail.com, please attempt manually.
 2020-08-31 | 14:49:36.899 | INFO  | Logged in as myusername(exxxxxxxxxx4)
 2020-08-31 | 14:49:39.851 | WARN  | Failed to claim Shadowrun Collection (Error: Unable to acquire purchase token)

**Comment by Dareeo** [comment]
but I can see there is fix for this issue
