### ISSUE TITLE
How to run automaticaly?

### ISSUE THREAD

**Issue by Dareeo** [Revadike/epicgames-freebies-claimer#54]
I finally managed to login today with this claimer, but I don't see the point of usage if it can't be automated. After login it log me out:

 2020-08-31 | 22:02:36.376 | WARN  | Invalid captcha!
 2020-08-31 | 22:02:36.388 | WARN  | Failed to login as email@gmail.com, please attempt manually.
You need to solve CAPTCHA!
 2020-08-31 | 22:05:59.208 | INFO  | Logged in as loginname(exxxxxxx0)
 2020-08-31 | 22:06:05.392 | INFO  | Shadowrun Collection was already claimed for this account
 2020-08-31 | 22:06:06.262 | INFO  | Logged loginname out of Epic Games

Next time when I run npm start it again ask to solve the 9 CAPTCHA dices which takes more time and effort as if log into the website directly, so I really don't understand how to automate this script.
So far I thought after login it wil stay in check and claim loop. It seems I was wrong. Or am I wrong? Thanks

**Comment by Revadike** [comment]
Yes, you can loop it. Check config.

**Comment by Dareeo** [comment]
Yes, I have checked it.
Config:
{
	"accounts": [
		{
			"email": "email@gmail.com",
			"password": "password",
			"secret": "696929", //2FA code
			"rememberLastSession": true
		}
	],
	"delay": 1440,
	"loop": true
}
log:https://pastebin.ubuntu.com/p/Fh7Z9YQ9r9/
A new browser opens at login page then navigate to https://www.epicgames.com/account/personal (i can see my account details, but after a few secs an error is thrown in cmd (timeout).
https://pastebin.ubuntu.com/p/wsCWCGRd9x/

**Comment by Revadike** [comment]
Can you verify if it's fixed? Closing this in the meanwhile...
