### ISSUE TITLE
Add gog.com to freebies

### ISSUE THREAD

**Issue by olepg** [Revadike/epicgames-freebies-claimer#55]
I know this repo is focused on epic games, but we all just want free games, no matter where they come from.

Gog.com has a very simple way of giving away content. All you have to do is log into your account and visit this URL:
https://www.gog.com/giveaway/claim

There's not always active give aways.

**Comment by Revadike** [comment]
Sorry, not the scope of this project. But seeing as it's that simple, why not build it yourself?
