### ISSUE TITLE
Never used node.js before. I want to use your script.

### ISSUE THREAD

**Issue by ZaHecc** [Revadike/epicgames-freebies-claimer#56]
I download node.js from google and your script. I'm unsure how to run it. I opened node.js and tried to type "nmp install". Nothing. I tried it in cmd. Also nothing. I really have no idea how to work with node.js but I'd really like to use your script if someone can break it down for me. <3

**Comment by Revadike** [comment]
where did you extract my project? what folder?

**Comment by ZaHecc** [comment]
Downloads folder

**Comment by Revadike** [comment]
absolute path?

**Comment by ZaHecc** [comment]
C:\Users\zath1\Documents\Downloads

**Comment by Revadike** [comment]
so, do this
1. Open CMD
2. Enter `CD /d "C:\Users\zath1\Documents\Downloads"`
3. Enter `npm install` and wait for it to be done
4. Enter `npm start USERNAME PASSWORD`

**Comment by ZaHecc** [comment]
It says:

'nmp' is not recognized as an internal or external command, 
operable program or batch file.

**Comment by Revadike** [comment]
N-P-M

**Comment by ZaHecc** [comment]
![image](https://user-images.githubusercontent.com/40443823/93527121-406c5300-f8ed-11ea-9f68-19dfa9d48a5d.png)

**Comment by Revadike** [comment]
I thought you installed node.js?
Do that first:
https://nodejs.org/dist/v12.18.4/node-v12.18.4-x64.msi

**Comment by ZaHecc** [comment]
I thought I did but maybe I installed it incorrectly somehow.
After installing that version and restarting cmd.
It's giving me the same error.

**Comment by ZaHecc** [comment]
![image](https://user-images.githubusercontent.com/40443823/93528581-65fa5c00-f8ef-11ea-986d-fcd98687592c.png)

**Comment by jejei** [comment]
did you run "npm install"
it can't find the node_modules folder, which is generated via that command
