### ISSUE TITLE
anyone could help me,plz

### ISSUE THREAD

**Issue by Frankklk** [Revadike/epicgames-freebies-claimer#63]
![image](https://user-images.githubusercontent.com/44097708/97067370-53123000-15ef-11eb-81ef-32f92c8ca0e1.png)
what should I do

**Comment by MrZeroLord** [comment]
![image](https://user-images.githubusercontent.com/40106969/97081861-8f508b00-1605-11eb-90b0-89de46cfe853.png)
idk, got the same issue

**Comment by MrZeroLord** [comment]
you are not allowed to remove the second email part inside the config.json file

**Comment by Revadike** [comment]
The config structure is wrong. I suggest you use a JSON validator like this one to check your syntax: https://jsononline.net/json-validator
