### ISSUE TITLE
 Unexpected token ] in JSON at position 156

### ISSUE THREAD

**Issue by MrZeroLord** [Revadike/epicgames-freebies-claimer#65]
![image](https://user-images.githubusercontent.com/40106969/97081970-7694a500-1606-11eb-9a54-7b25e990173e.png)

**Comment by MrZeroLord** [comment]
![image](https://user-images.githubusercontent.com/40106969/97081985-8f9d5600-1606-11eb-9653-9e3a078101ff.png)

**Comment by MrZeroLord** [comment]
![image](https://user-images.githubusercontent.com/40106969/97082001-a93e9d80-1606-11eb-94a5-4bc36f344719.png)

**Comment by MrZeroLord** [comment]
no way to remove the second email? sadge

**Comment by Revadike** [comment]
Remove the trailing comma
