### ISSUE TITLE
Error after input captcha

### ISSUE THREAD

**Issue by arisawali2014** [Revadike/epicgames-freebies-claimer#69]
![gambar](https://user-images.githubusercontent.com/31904944/102444387-b2267b00-405b-11eb-8834-a2147fd5df34.png)
I have entered captcha and the code manually. got this error

**Comment by Stinosko** [comment]
I had the same issue today too

**Comment by qsevers23** [comment]
It appears that the `ID` for the button has changed to `#sign-in`, as well as the addition of the captcha. You can combat this by pausing before line 123 of index.js during debug and entering the captcha yourself.

**Comment by Stinosko** [comment]
I didn't use a debugger but i filled in the captcha in time and it still times-out for some reason. Is using a debugger actually needed?

**Comment by qsevers23** [comment]
> I didn't use a debugger but i filled in the captcha in time and it still times-out for some reason. Is using a debugger actually needed?

Do you have a stacktrace?

**Comment by Stinosko** [comment]
Oooh wait i forgot to switch line 119 `#login` to `#sign-in`. My bad! Now it works 🙂

**Comment by arisawali2014** [comment]
> 
> 
> It appears that the `ID` for the button has changed to `#sign-in`, as well as the addition of the captcha. You can combat this by pausing before line 123 of index.js during debug and entering the captcha yourself.

![gambar](https://user-images.githubusercontent.com/31904944/102564007-22d9a000-410d-11eb-8e04-4265d2b6d2c7.png)

Wow that actually worked

**Comment by arisawali2014** [comment]
![gambar](https://user-images.githubusercontent.com/31904944/102564591-549f3680-410e-11eb-82b6-aa27f07b5ff6.png)
After i restarted it goes error again. the chrome showing to personal account not to login menu

**Comment by Revadike** [comment]
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/66
