### ISSUE TITLE
ESOCKETTIMEOUT, ECONNRESET and more.

### ISSUE THREAD

**Issue by MusTangLee** [Revadike/epicgames-freebies-claimer#7]
Getting a few different errors, I would guess the end cause to be timeout related.
Still investigating. In the past few days even pinging epicstore.com returns timeout sometimes (even with a fast vpn to different locations around the world).
Important to note, the accounts I'm testing these on does NOT have 2FA.

> Logged in as *******
> Close to the Sun was already claimed for this account
> Error: ESOCKETTIMEDOUT
>     at ClientRequest.<anonymous> (****\epicgames-freebies-claimer\node_modules\request\request.js:816:19)
>     at Object.onceWrapper (events.js:427:28)
>     at ClientRequest.emit (events.js:321:20)
>     at TLSSocket.emitRequestTimeout (_http_client.js:721:9)
>     at Object.onceWrapper (events.js:427:28)
>     at TLSSocket.emit (events.js:321:20)
>     at TLSSocket.Socket._onTimeout (net.js:478:8)
>     at listOnTimeout (internal/timers.js:549:17)
>     at processTimers (internal/timers.js:492:7) {
>   code: 'ESOCKETTIMEDOUT',
>   connect: false
> }

Connection reset error:

> Failed to login as ***, please attempt manually.
> Error: net::ERR_CONNECTION_RESET at https://epicgames.com/id
>     at navigate *****\epicgames-freebies-claimer\node_modules\puppeteer\lib\FrameManager.js:120:37)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async FrameManager.navigateFrame *****\epicgames-freebies-claimer\node_modules\puppeteer\lib\FrameManager.js:94:17)
>     at async Frame.goto *****\epicgames-freebies-claimer\node_modules\puppeteer\lib\FrameManager.js:406:12)
>     at async Page.goto (*****\epicgames-freebies-claimer\node_modules\puppeteer\lib\Page.js:672:12)
>     at async Function.init (*****\epicgames-freebies-claimer\node_modules\epicgames-client-login-adapter\index.js:53:5)
>     at async *****\epicgames-freebies-claimer\gimme_free_epic_shit.js:21:20
>   -- ASYNC --
>     at Frame.<anonymous> (*****\epicgames-freebies-claimer\node_modules\puppeteer\lib\helper.js:111:15)
>     at Page.goto (*****\epicgames-freebies-claimer\node_modules\puppeteer\lib\Page.js:672:49)
>     at Page.<anonymous> (*****\epicgames-freebies-claimer\node_modules\puppeteer\lib\helper.js:112:23)
>     at Function.init (*****\epicgames-freebies-claimer\node_modules\epicgames-client-login-adapter\index.js:53:16)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async *****\epicgames-freebies-claimer\gimme_free_epic_shit.js:21:20

Unknown quick purchase:

> Failed to login as ******, please attempt manually.
> Logged in as ********
> Close to the Sun was already claimed for this account
> Sherlock Holmes Crimes and Punishments was already claimed for this account
> Error: Unknown quick purchase status: false
>     at Launcher.purchase (******\epicgames-freebies-claimer\node_modules\epicgames-client\src\Client\index.js:645:15)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async *******\epicgames-freebies-claimer\gimme_free_epic_shit.js:52:29

ECONNRESET:

> Failed to login as *****, please attempt manually.
> Logged in as *********
> Close to the Sun was already claimed for this account
> Sherlock Holmes Crimes and Punishments was already claimed for this account
> Error: read ECONNRESET
>     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
>   errno: -4077,
>   code: 'ECONNRESET',
>   syscall: 'read'
> }

Categories of undefined:

> Failed to login as *****, please attempt manually.
> Logged in as undefined (*****)
> TypeError: Cannot read property 'categories' of undefined
>     at *****\epicgames-freebies-claimer\gimme_free_epic_shit.js:43:30
>     at Array.filter (<anonymous>)
>     at ****\epicgames-freebies-claimer\gimme_free_epic_shit.js:43:10
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)

currentPrice of undefined:

> Logged in as *******
> Close to the Sun was already claimed for this account
> TypeError: Cannot read property 'currentPrice' of undefined
>     at ****\epicgames-freebies-claimer\gimme_free_epic_shit.js:49:53
>     at Array.filter (<anonymous>)
>     at ****\epicgames-freebies-claimer\gimme_free_epic_shit.js:49:33
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)

Note these last 2 are very wierd, probably getting the offers per namespace fails?

Btw this still pops up even after the recent login fix by epicgames-client module and epicgames-client-login-adapter:

> Error: Error while initialize process.
>     at *****\epicgames-freebies-claimer\gimme_free_epic_shit.js:12:15
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)

it might be best to post some of these issues on node-epicgames-client repo? probably.

**Comment by Revadike** [comment]
> it might be best to post some of these issues on node-epicgames-client repo? probably.

Yes, probably. I'll leave it open, just in case you know more.

**Comment by Revadike** [comment]
Seems to be a problem with your network, not `epicgames-freebies-claimer`.
