### ISSUE TITLE
Can I run this on a headless server?

### ISSUE THREAD

**Issue by dorkage** [Revadike/epicgames-freebies-claimer#72]
I'm attempting to get this working on my headless server, Ubuntu 20.10 LXC container on a Proxmox host. I thought it would work since the requisites didn't mention anything else, but this is also my first time using Node.JS.

Here's the logs I'm getting.

> 
> root@Node:~/epicgames-freebies-claimer-master# npm start *************** *************** 0|1 ******
> 1: command not found
> internal/modules/cjs/loader.js:1175
>     throw err;
>     ^
> 
> SyntaxError: /root/epicgames-freebies-claimer-master/config.json: Unexpected token p in JSON at position 32
>     at parse (<anonymous>)
>     at Object.Module._extensions..json (internal/modules/cjs/loader.js:1172:22)
>     at Module.load (internal/modules/cjs/loader.js:986:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
>     at Module.require (internal/modules/cjs/loader.js:1026:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (/root/epicgames-freebies-claimer-master/claimer.js:5:16)
>     at Module._compile (internal/modules/cjs/loader.js:1138:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
>     at Module.load (internal/modules/cjs/loader.js:986:32)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! epicgames-freebies-claimer@1.4.1 start: `node claimer.js "***************" "***************" "0"`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the epicgames-freebies-claimer@1.4.1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-12-25T18_29_16_159Z-debug.log
> 
> 

Actual Error Log

> 
>  info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   '/usr/bin/node',
> 1 verbose cli   '/usr/bin/npm',
> 1 verbose cli   'start',
> 1 verbose cli   '***************',
> 1 verbose cli   '***************',
> 1 verbose cli   '0'
> 1 verbose cli ]
> 2 info using npm@6.14.8
> 3 info using node@v12.18.2
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle epicgames-freebies-claimer@1.4.1~prestart: epicgames-freebies-claimer@1.4.1
> 6 info lifecycle epicgames-freebies-claimer@1.4.1~start: epicgames-freebies-claimer@1.4.1
> 7 verbose lifecycle epicgames-freebies-claimer@1.4.1~start: unsafe-perm in lifecycle true
> 8 verbose lifecycle epicgames-freebies-claimer@1.4.1~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/epicgames-freebies-claimer-master/node_modu>
> 9 verbose lifecycle epicgames-freebies-claimer@1.4.1~start: CWD: /root/epicgames-freebies-claimer-master
> 10 silly lifecycle epicgames-freebies-claimer@1.4.1~start: Args: [
> 10 silly lifecycle   '-c',
> 10 silly lifecycle   'node claimer.js "***************" "***************" "0"'
> 10 silly lifecycle ]
> 11 silly lifecycle epicgames-freebies-claimer@1.4.1~start: Returned: code: 1  signal: null
> 12 info lifecycle epicgames-freebies-claimer@1.4.1~start: Failed to exec start script
> 13 verbose stack Error: epicgames-freebies-claimer@1.4.1 start: `node claimer.js "***************" "***************" "0"`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:315:20)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:315:20)
> 13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> 14 verbose pkgid epicgames-freebies-claimer@1.4.1
> 15 verbose cwd /root/epicgames-freebies-claimer-master
> 16 verbose Linux 5.4.78-2-pve
> 17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "***************" "***************" "0"
> 18 verbose node v12.18.2
> 19 verbose npm  v6.14.8
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error epicgames-freebies-claimer@1.4.1 start: `node claimer.js "***************" "***************" "0"`
> 22 error Exit status 1
> 23 error Failed at the epicgames-freebies-claimer@1.4.1 start script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by Revadike** [comment]
Unless you want to implement a paid captcha service, I don't think you will be able to use this in a headless environment.

**Comment by Revadike** [comment]
Also appears your config.json syntax is invalid. Fix this.
