### ISSUE TITLE
Hey, so um, I don’t know what to do..

### ISSUE THREAD

**Issue by FlickZexe** [Revadike/epicgames-freebies-claimer#74]
As the title says, I really don’t understand this. If someone can do a youtube video of how to do this? :/

**Comment by JonathanTreffler** [comment]
https://github.com/xuac/claim-epic-freebies may be easier (it runs this software, but in a github workflow)

**Comment by Revadike** [comment]
Please follow https://github.com/Revadike/epicgames-freebies-claimer#instructions
