### ISSUE TITLE
Verbose stack error?

### ISSUE THREAD

**Issue by FlickZexe** [Revadike/epicgames-freebies-claimer#76]
So it gave me error in phase "npm start"

Looked into logs and found this command failed:

> 23 verbose stack Error: command failed
> 23 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
> 23 verbose stack     at ChildProcess.emit (node:events:376:20)
> 23 verbose stack     at maybeClose (node:internal/child_process:1063:16)
> 23 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
> 24 verbose pkgid epicgames-freebies-claimer@1.4.1
> 25 verbose cwd C:\Users\FlickZ\Downloads\epicgames-freebies-claimer-master
> 26 verbose Windows_NT 10.0.19042
> 27 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
> 28 verbose node v15.5.0
> 29 verbose npm  v7.3.0
> 30 error code 1
> 31 error path C:\Users\FlickZ\Downloads\epicgames-freebies-claimer-master
> 32 error command failed
> 33 error command C:\WINDOWS\system32\cmd.exe /d /s /c node claimer.js
> 34 verbose exit 1
>

**Comment by Revadike** [comment]
Could you verify if this is fixed with the latest version? Closing this for now...
