### ISSUE TITLE
Hiding the script.

### ISSUE THREAD

**Issue by Jusp3** [Revadike/epicgames-freebies-claimer#79]
Anybody have tried to fully hide the operation on Windows 10.
My problem is that when i play a game and the script goes on windows loses focus on the game and it focuses to the script.
I need help!
Thank you.

**Comment by Revadike** [comment]
I used despot to minimize cmd to tray in the past

**Comment by Jusp3** [comment]
Can you give me any links?

**Comment by Revadike** [comment]
dexpot i meant

**Comment by Revadike** [comment]
https://www.dexpot.de/index.php?lang=en

**Comment by Jusp3** [comment]
ok maybe i can found something now
Thank you!

**Comment by Jusp3** [comment]
> https://www.dexpot.de/index.php?lang=en

My CMD is going to desktop 2 when i open it on desktop 1 have you fixed that issue?

**Comment by Jusp3** [comment]
Now i found how to do it sorry for bother.
