### ISSUE TITLE
When the browser open, nothing happens

### ISSUE THREAD

**Issue by gratv** [Revadike/epicgames-freebies-claimer#80]
Just open a CMD with this message

> 2020-12-30 | 14:06:18.495 | ERROR | TimeoutError: Timeout exceeded while waiting for event    at Timeout.<anonymous> (D:\Program Files\epicgames-freebies-claimer-master\node_modules\puppeteer\lib\helper.js:200:24)
>     at listOnTimeout (internal/timers.js:554:17)
>     at processTimers (internal/timers.js:497:7)
>   -- ASYNC --
>     at Page.<anonymous> (D:\Program Files\epicgames-freebies-claimer-master\node_modules\puppeteer\lib\helper.js:111:15)
>     at Function.init (D:\Program Files\epicgames-freebies-claimer-master\node_modules\epicgames-client-login-adapter\index.js:110:16)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async D:\Program Files\epicgames-freebies-claimer-master\claimer.js:79:28
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! epicgames-freebies-claimer@1.4.1 start: `node claimer.js "*"`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the epicgames-freebies-claimer@1.4.1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\MYUSER\AppData\Roaming\npm-cache\_logs\2020-12-30T17_06_19_084Z-debug.log

I tried change the file
_\epicgames-freebies-claimer-master\node_modules\puppeteer\lib\**TimeoutSettings.js**_ from 30000 to 120000

**_Inside the log file_**

> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Users\\MYUSER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'start',
> 1 verbose cli   '*'
> 1 verbose cli ]
> 2 info using npm@6.14.10
> 3 info using node@v14.15.3
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle epicgames-freebies-claimer@1.4.1~prestart: epicgames-freebies-claimer@1.4.1
> 6 info lifecycle epicgames-freebies-claimer@1.4.1~start: epicgames-freebies-claimer@1.4.1
> 7 verbose lifecycle epicgames-freebies-claimer@1.4.1~start: unsafe-perm in lifecycle true
> 8 verbose lifecycle epicgames-freebies-claimer@1.4.1~start: PATH: C:\Users\MYUSER\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Program Files\epicgames-freebies-claimer-master\node_modules\.bin;C:\Program Files (x86)\Touch Portal\plugins\adb\platform-tools;C:\Program Files\nodejs\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;"C:;C:\WINDOWS;C:\WINDOWS\system32";c:\windows\system32;C:\Program Files\Git\cmd;C:\Program Files\Git\bin;C:\Users\MYUSER\AppData\Roaming\npm;C:\Users\MYUSER\AppData\Local\Streamlink\bin;C:\Users\MYUSER\AppData\Local\Microsoft\WindowsApps;C:\Users\MYUSER\AppData\Roaming\npm;C:\Windows;C:\Windows\system32;"C:;C:\WINDOWS;C:\WINDOWS\system32";c:\windows\system32;C:\Program Files\Git\bin;C:\Program Files\Git\cmd;
> 9 verbose lifecycle epicgames-freebies-claimer@1.4.1~start: CWD: D:\Program Files\epicgames-freebies-claimer-master
> 10 silly lifecycle epicgames-freebies-claimer@1.4.1~start: Args: [ '/d /s /c', 'node claimer.js "*"' ]
> 11 silly lifecycle epicgames-freebies-claimer@1.4.1~start: Returned: code: 1  signal: null
> 12 info lifecycle epicgames-freebies-claimer@1.4.1~start: Failed to exec start script
> 13 verbose stack Error: epicgames-freebies-claimer@1.4.1 start: `node claimer.js "*"`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Users\MYUSER\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:315:20)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Users\MYUSER\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:315:20)
> 13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
> 14 verbose pkgid epicgames-freebies-claimer@1.4.1
> 15 verbose cwd D:\Program Files\epicgames-freebies-claimer-master
> 16 verbose Windows_NT 10.0.19042
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MYUSER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start" "*"
> 18 verbose node v14.15.3
> 19 verbose npm  v6.14.10
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error epicgames-freebies-claimer@1.4.1 start: `node claimer.js "*"`
> 22 error Exit status 1
> 23 error Failed at the epicgames-freebies-claimer@1.4.1 start script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by Revadike** [comment]
No longer relevant, it uses device auth now.
