### ISSUE TITLE
i tried this

### ISSUE THREAD

**Issue by amazing355** [Revadike/epicgames-freebies-claimer#83]
https://user-images.githubusercontent.com/26679868/104557628-a1fdbd80-5652-11eb-889d-2898027aa4dd.png
it doesn't work

**Comment by Revadike** [comment]
Please stop opening new issues.

**Comment by amazing355** [comment]
> Please stop opening new issues.

I said it doesn't work but you said please stop. If you solve my problem and I stop opening new issues!

**Comment by Revadike** [comment]
I did

**Comment by amazing355** [comment]
> I did

if you want i'll make a video?

**Comment by Revadike** [comment]
What you have shown me, I can tell you, you're doing it very wrong. I sent you the correct link to download or clone the project.

**Comment by amazing355** [comment]
> What you have shown me, I can tell you, you're doing it very wrong. I sent you the correct link to download or clone the project.

download or clone okay thanks I solved this <3

**Comment by amazing355** [comment]
> What you have shown me, I can tell you, you're doing it very wrong. I sent you the correct link to download or clone the project.
![i cant understand](https://user-images.githubusercontent.com/26679868/104648918-f2156800-56c4-11eb-9261-e6bb941c1aa1.png)

**Comment by Revadike** [comment]
[You are doing it wrong](http://letmegooglethat.com/?q=how+to+clone+or+download+from+github)

**Comment by amazing355** [comment]
> [You are doing it wrong](http://letmegooglethat.com/?q=how+to+clone+or+download+from+github)

![i cant](https://user-images.githubusercontent.com/26679868/104650615-841e7000-56c7-11eb-962e-87a3b66510d3.png)
