### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by yanygm** [Revadike/epicgames-freebies-claimer#86]
Run cd workdir
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated cheerio-select-tmp@0.1.1: Use cheerio-select instead
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> puppeteer@2.1.1 install /home/runner/work/EpicGamesGiveawaysAutoClaimer/EpicGamesGiveawaysAutoClaimer/workdir/node_modules/puppeteer
> node install.js

Chromium downloaded to /home/runner/work/EpicGamesGiveawaysAutoClaimer/EpicGamesGiveawaysAutoClaimer/workdir/node_modules/puppeteer/.local-chromium/linux-722234
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN xmpp-jid@1.3.0 requires a peer of node-stringprep@^0.8.0 but none is installed. You must install peer dependencies yourself.

added 323 packages from 210 contributors and audited 324 packages in 17.11s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Error: Process completed with exit code 1.

**Comment by Revadike** [comment]
Wrong GitHub repository buddy
