### ISSUE TITLE
invalid captcha on raspeberry pi

### ISSUE THREAD

**Issue by Lolozendev** [Revadike/epicgames-freebies-claimer#87]
I'm trying to run it on my raspberry but I keep getting this error
![image](https://user-images.githubusercontent.com/41087061/108441064-a2423780-7254-11eb-996e-245a40408b34.png)
And this weird file appeared
![image](https://user-images.githubusercontent.com/41087061/108441103-b71ecb00-7254-11eb-97b7-8d11d660af7b.png)

any solution ?

**Comment by LaserKaspar** [comment]
Same here... but not on raspberry

**Comment by Revadike** [comment]
Looks like `puppeteer` isn't installed properly.
Try `npm uninstall puppeteer` and then `npm install puppeteer` in the root directory.

**Comment by Lolozendev** [comment]
uninstalling and re installing it resulted in the same issue :/

**Comment by LaserKaspar** [comment]
I use the github actions script so there is nothing I could reinstall. I think so at least.

**Comment by mt025** [comment]
Not sure if puppeteer is supported for ARM, I've always had trouble in the past. The config.json file lets you pass options to puppeteer. I have chrome installed so instead of the bunlded puppeteer chrome I use the system version.

```
{
	"accounts": [
		{
			"email": "REDACTED",
			"password": "",
			"secret": "",
			"rememberLastSession": true
		}
	],
	"options": {
		"puppeteer" : {
			"executablePath" : "/usr/bin/chromium-browser"
		}
	},
	"delay": 1440,
	"loop": true
}
```

**Comment by Revadike** [comment]
It no longer uses puppeteer or chrome, please update
