### ISSUE TITLE
cant find epicgames-client.

### ISSUE THREAD

**Issue by Pr0xyblade** [Revadike/epicgames-freebies-claimer#88]
i npm installed, didnt complete correctly so just ran and was gonna install missing modules. epicgames-client was missing but when i install that it npm cant find it

![image](https://user-images.githubusercontent.com/72248782/108670056-188bb600-7543-11eb-9f8b-ab4fea256ab0.png)

**Comment by Revadike** [comment]
`npm install`

**Comment by gerrie0** [comment]
do u have git installed?

**Comment by Revadike** [comment]
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/44
