### ISSUE TITLE
npm install not successfully running

### ISSUE THREAD

**Issue by KeneePatel** [Revadike/epicgames-freebies-claimer#89]
So I am an Arch Linux user. I have the NPM 7.6 version with the latest node.js. But it's giving a lot of errors and ofc the npm start then says modules not found. So is this claimer Windows specific somehow?

**Comment by josephnglynn** [comment]
> So I am an Arch Linux user. I have the NPM 7.6 version with the latest node.js. But it's giving a lot of errors and ofc the npm start then says modules not found. So is this claimer Windows specific somehow?

I'm running arch and I managed to get it to run. I downloaded it from releases page and updated epicgames-client-login-adapter in the package json to the latest version

**Comment by Revadike** [comment]
It is not windows specific.
