### ISSUE TITLE
Doesn't claim the games.

### ISSUE THREAD

**Issue by Speeedyyyy** [Revadike/epicgames-freebies-claimer#9]
Says it is already claimed, when it isn't. Tried replacing it with quickPurchase, but it ends on checkout. Also tried purchaseOrderConfirmed but I get an error. Gonna try to solve but would appriciate some help.

**Comment by MusTangLee** [comment]
Just tried this now on more than 1 account and it claims the games...
Can you give additional information? Maybe the text in the console (blurr out your information and account token!)

Do not change Purchase to quickPurchase. It won't work since the purchase is getting stuck on CHECKOUT status.

**Comment by rheasbelt** [comment]
Have the same problem with VPN enabled. Everything is fine without it. I think epicgames might blacklist some subnets to prevent them from accessing particular urls. In this case exactly this function fails:
https://github.com/SzymonLisowiec/node-epicgames-client/blob/48f251b98a56cfa2a4501967cfae6e4a91ad051a/src/Client/index.js#L559

It returns an error html page:
![2020-04-18_02-54](https://user-images.githubusercontent.com/58597979/79622469-0f121000-8120-11ea-869c-b6a0bdd5605e.png)

**Comment by rheasbelt** [comment]
Also there is a related thread already: https://github.com/Revadike/epicgames-freebies-claimer/issues/5
