### ISSUE TITLE
Python and Visual Studio Requirements, Missing Prerequisites

### ISSUE THREAD

**Issue by MaximumPotato** [Revadike/epicgames-freebies-claimer#91]
On running `npm install`, I was initially getting complaints that I didn't have Python installed on my system. I figured it would be a quick fix, so I installed python 3 and ran the install command again. This time, it started complaining about not being able to find Visual Studio as seen below. Neither of these are listed as requirements for installing the package. 

> C:\Users\Core\epicgames-freebies-claimer>npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'node-stringprep@0.8.0',
npm WARN EBADENGINE   required: { node: '>=0.8 <=0.12' },
npm WARN EBADENGINE   current: { node: 'v15.9.0', npm: '7.5.3' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated cheerio-select-tmp@0.1.1: Use cheerio-select instead
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Core\\epicgames-freebies-claimer\\node_modules',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Core\epicgames-freebies-claimer\node_modules\puppeteer'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Core\\epicgames-freebies-claimer\\node_modules\\puppeteer'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\Core\epicgames-freebies-claimer\node_modules\node-stringprep
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.9.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.2 found at "C:\Users\Core\AppData\Local\Programs\Python\Python39\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (D:\Library\programs\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at D:\Library\programs\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\Library\programs\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at D:\Library\programs\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at D:\Library\programs\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at D:\Library\programs\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at D:\Library\programs\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "D:\\Library\\programs\\nodejs\\node.exe" "D:\\Library\\programs\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Core\epicgames-freebies-claimer\node_modules\node-stringprep
npm ERR! gyp ERR! node -v v15.9.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

**Comment by Revadike** [comment]
Run `C:\Program Files\nodejs\install_tools.bat`

**Comment by MaximumPotato** [comment]
Alright, that solved that issue. You might want to mention in the Readme that the extra tools in the node installer are required, as well as the location of that script for those with issues.

I've unfortunately got another issue now. I'll drop it here but let me know if you would prefer another ticket be created.

Settings are in the config file, `npm install` was run twice. Once for initial setup, once to try and resolve the issue. Similar to #88?

> PS C:\Users\Core\epicgames-freebies-claimer> npm start
> epicgames-freebies-claimer@1.4.1 start
> node claimer.js
> node:internal/modules/cjs/loader:926
>   throw err;
>   ^
> Error: Cannot find module 'mime'
> Require stack:
> - C:\Users\Core\epicgames-freebies-claimer\node_modules\puppeteer\lib\Page.js
> - C:\Users\Core\epicgames-freebies-claimer\node_modules\puppeteer\lib\Target.js
> - C:\Users\Core\epicgames-freebies-claimer\node_modules\puppeteer\lib\Browser.js
> - C:\Users\Core\epicgames-freebies-claimer\node_modules\puppeteer\lib\api.js
> - C:\Users\Core\epicgames-freebies-claimer\node_modules\puppeteer\index.js
> - C:\Users\Core\epicgames-freebies-claimer\node_modules\epicgames-client-login-adapter\index.js
> - C:\Users\Core\epicgames-freebies-claimer\claimer.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:768:27)
>     at Module.require (node:internal/modules/cjs/loader:995:19)
>     at require (node:internal/modules/cjs/helpers:92:18)
>     at Object.<anonymous> (C:\Users\Core\epicgames-freebies-claimer\node_modules\puppeteer\lib\Page.js:19:14)
>     at Module._compile (node:internal/modules/cjs/loader:1091:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
>     at Module.load (node:internal/modules/cjs/loader:971:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:812:14)
>     at Module.require (node:internal/modules/cjs/loader:995:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'C:\\Users\\Core\\epicgames-freebies-claimer\\node_modules\\puppeteer\\lib\\Page.js',
>     'C:\\Users\\Core\\epicgames-freebies-claimer\\node_modules\\puppeteer\\lib\\Target.js',
>     'C:\\Users\\Core\\epicgames-freebies-claimer\\node_modules\\puppeteer\\lib\\Browser.js',
>     'C:\\Users\\Core\\epicgames-freebies-claimer\\node_modules\\puppeteer\\lib\\api.js',
>     'C:\\Users\\Core\\epicgames-freebies-claimer\\node_modules\\puppeteer\\index.js',
>     'C:\\Users\\Core\\epicgames-freebies-claimer\\node_modules\\epicgames-client-login-adapter\\index.js',
>     'C:\\Users\\Core\\epicgames-freebies-claimer\\claimer.js'
>   ]
> }
> npm ERR! code 1
> npm ERR! path C:\Users\Core\epicgames-freebies-claimer
> npm ERR! command failed
> npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node claimer.js
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\ProgramData\npm\npm-cache\_logs\2021-04-01T18_54_01_669Z-debug.log

**Comment by MaximumPotato** [comment]
I manually installed `mime`, and then `extract-zip`. Feels like `install` missed a lot of stuff.

**Comment by MaximumPotato** [comment]
Starting over and creating the `.egstore` directory manually seems to have fixed everything. Hopefully this little journey might help someone in the future!
