### ISSUE TITLE
Cant even install it.

### ISSUE THREAD

**Issue by Justin163** [Revadike/epicgames-freebies-claimer#94]
When trying to run the npm install and then the file, it just says that the file doesnt contain the package file and stuff.

![installlog](https://user-images.githubusercontent.com/83575899/116853809-a8458480-abc4-11eb-8437-3b93fa7673a8.png)

I don't know if im doing something wrong or if the file is just broken.

**Comment by Revadike** [comment]
You executed the command wrongly. Do this instead:
1. `cd /d C:\Users\Justi\Desktop\epicgames-freebies-claimer-master`
2. `npm install`
