### ISSUE TITLE
Suggestion: Windows wrapper to run hidden/minimize to tray on startup

### ISSUE THREAD

**Issue by lucifudge** [Revadike/epicgames-freebies-claimer#97]
### Current Behavior (if any): 

Node.js command prompt can be minimized, but not to system tray

### Desired Behavior: 

Allow the script to minimize to tray by running it in some kind of wrapper

### Motivation / Use Case for Changing the Behavior: 

Using this in a Windows environment and would like to be able to have it run on startup with less chance of accidentally closing it due to running in taskbar/foreground or taking up taskbar real estate

**edit: resolved using NSSM - the Non-Sucking Service Manager, although it is public domain license and would be cool to see baked directly into the freebies claimer**

**Comment by lucifudge** [comment]
resolved using NSSM - the Non-Sucking Service Manager, although it is public domain license and would be cool to see baked directly into the freebies claimer

**Comment by Revadike** [comment]
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/79
