### ISSUE TITLE
Error when starting script

### ISSUE THREAD

**Issue by THE-AWESOME-ONE** [Revadike/epicgames-freebies-claimer#98]
### Expected Behavior
Logging in

### Actual Behavior
C:\Users\username\epicgames>npm start

> epicgames-freebies-claimer@1.5.0 start C:\Users\username\epicgames
> node claimer.js

To generate device auth, please provide an exchange code for the email: device_id : 5555eeccffbb77dd11667To generate device auth, please provide an exchange code for the email: device_id : 55ecfb7d16744578bd76e44ee00334433eexxxxxx

 2021-05-31 | 17:18:11.717 | ERROR | Error: errors.com.epicgames.account.oauth.exchange_code_not_found
    at Request._callback (C:\Users\username\epicgames\node_modules\epicgames-client\src\Http.js:106:23)
    at Request.self.callback (C:\Users\username\epicgames\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\username\epicgames\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\username\epicgames\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  response: <ref *1> IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function (anonymous)],
      error: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'account-public-service-prod03.ol.epicgames.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'account-public-service-prod03.ol.epicgames.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      timeout: 30000,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 149,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 30000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 7266,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 164,
        [Symbol(triggerId)]: 158
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      date: 'Mon, 31 May 2021 22:18:11 GMT',
      'content-type': 'application/json;charset=utf-8',
      'content-length': '437',
      connection: 'close',
      'x-epic-error-code': '18057',
      'x-epic-error-name': 'errors.com.epicgames.account.oauth.exchange_code_not_found',
      'cache-control': 'no-cache, no-store, no-transform',
      'x-epic-correlation-id': '909340b6-36d4-4baa-9942-343f47b868ff'
    },
    rawHeaders: [
      'Date',
      'Mon, 31 May 2021 22:18:11 GMT',
      'Content-Type',
      'application/json;charset=utf-8',
      'Content-Length',
      '437',
      'Connection',
      'close',
      'X-Epic-Error-Code',
      '18057',
      'X-Epic-Error-Name',
      'errors.com.epicgames.account.oauth.exchange_code_not_found',
      'Cache-Control',
      'no-cache, no-store, no-transform',
      'X-Epic-Correlation-ID',
      '909340b6-36d4-4baa-9942-343f47b868ff'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 400,
    statusMessage: 'Bad Request',
    client: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'account-public-service-prod03.ol.epicgames.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'account-public-service-prod03.ol.epicgames.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      timeout: 30000,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 149,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 30000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 7266,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 164,
        [Symbol(triggerId)]: 158
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /account/api/oauth/token HTTP/1.1\r\n' +
        'Accept-Language: en-EN\r\n' +
        'Authorization: basic MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=\r\n' +
        'User-Agent: EpicGamesLauncher/++Fortnite+Release-12.30-CL-12493283 Windows/10.0.17134.1.768.64bit\r\n' +
        'x-xsrf-token: c38a4c44be1c4ca7aa9af4d2aff95cb5\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'host: account-public-service-prod03.ol.epicgames.com\r\n' +
        'cookie: EPIC_DEVICE=1efef7a97c564e66865c05bc553c91ae\r\n' +
        'accept: application/json\r\n' +
        'content-length: 104\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/account/api/oauth/token',
      _ended: true,
      res: [Circular *1],
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'account-public-service-prod03.ol.epicgames.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      timeout: 30000,
      headers: [Object],
      method: 'POST',
      callback: [Function (anonymous)],
      readable: true,
      writable: true,
      explicitMethod: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      setHeader: [Function (anonymous)],
      hasHeader: [Function (anonymous)],
      getHeader: [Function (anonymous)],
      removeHeader: [Function (anonymous)],
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function (anonymous)],
      uri: [Url],
      proxy: null,
      tunnel: true,
      setHost: true,
      originalCookieHeader: undefined,
      _jar: [RequestJar],
      port: 443,
      host: 'account-public-service-prod03.ol.epicgames.com',
      body: 'grant_type=exchange_code&exchange_code=55ecfb7d16744578bd76e4e0343e5b82&includePerms=true&token_type=eg1',
      path: '/account/api/oauth/token',
      _json: true,
      httpModule: [Object],
      agentClass: [Function: Agent],
      agent: [Agent],
      _started: true,
      href: 'https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token',
      req: [ClientRequest],
      ntick: true,
      timeoutTimer: null,
      response: [Circular *1],
      originalHost: 'account-public-service-prod03.ol.epicgames.com',
      originalHostHeaderName: 'host',
      responseContent: [Circular *1],
      _destdata: true,
      _ended: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: {
      errorCode: 'errors.com.epicgames.account.oauth.exchange_code_not_found',
      errorMessage: 'Sorry the exchange code you supplied was not found. It is possible that it was no longer valid',
      messageVars: [],
      numericErrorCode: 18057,
      originatingService: 'com.epicgames.account.public',
      intent: 'prod',
      error_description: 'Sorry the exchange code you supplied was not found. It is possible that it was no longer valid',
      error: 'invalid_grant'
    },
    [Symbol(kCapture)]: false,
    [Symbol(RequestTimeout)]: undefined
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epicgames-freebies-claimer@1.5.0 start: `node claimer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epicgames-freebies-claimer@1.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2021-05-31T22_18_11_805Z-debug.log

(Last 6 digits of device ID replaced with x for privacy
There is also a glitch when it is pasted or typed in
Not sure if it is related to this script particularly or CMD)
### Steps to Reproduce the Problem

  1.  npm start
  2. Pasting in device ID
  3. 

### Specifications

  - Platform/OS: Windows 10
  - Node Version: v14.16.1
  - `epicgames-freebies-claimer` Version: V1.5.0

**Comment by Revadike** [comment]
Put `device_auths.json` in your project root dir.

**Comment by THE-AWESOME-ONE** [comment]
I already did

**Comment by THE-AWESOME-ONE** [comment]
Here are the contents of the file:
{
    "device_id": "55ecfb7d16744578bd76e4e034xxxxxx",
    "account_id": "xxxx",
    "secret": "xxxx",
    "user_agent": "DeviceAuthGenerator/1.0.0 Windows/10.0.19041",
    "created": {
        "location": "City, United States",
        "ip_address": "x.x.x.x",
        "datetime": "2021-05-31T22:15:26.871Z"
    }
}

**Comment by Revadike** [comment]
The file is somehow not detected. Perhaps you have a different working directory?
